## Notebook for formatting data frames for phase association

In [1]:
import pandas as pd
import numpy as np
import glob

## 1. Format data frames for picks

### 1.1 Format one data frame first

In [3]:
df_FS09B_20121001 = pd.read_csv('../catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121001.csv')

In [4]:
df_FS09B_20121001

,Unnamed: 0,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival
0,0,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T00:04:09.141700Z
1,1,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T00:36:41.601700Z
2,2,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T00:55:43.061700Z
3,3,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T01:16:07.681700Z
4,4,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T01:41:37.561700Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,203,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T22:53:32.401700Z,NaN
204,204,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T23:25:19.181700Z,NaN
205,205,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T23:31:08.241700Z,NaN
206,206,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T23:49:13.461700Z,NaN
207,207,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T23:56:56.121700Z,NaN

In [5]:
df_FS09B_20121001['phase'] = np.nan
df_FS09B_20121001

,Unnamed: 0,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,...,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival,phase
0,0,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T00:04:09.141700Z,NaN
1,1,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T00:36:41.601700Z,NaN
2,2,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T00:55:43.061700Z,NaN
3,3,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T01:16:07.681700Z,NaN
4,4,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,NaN,2012-10-01T01:41:37.561700Z,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,203,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T22:53:32.401700Z,NaN,NaN
204,204,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T23:25:19.181700Z,NaN,NaN
205,205,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T23:31:08.241700Z,NaN,NaN
206,206,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T23:49:13.461700Z,NaN,NaN
207,207,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,...,50.0,2012-10-01T00:00:00.001700Z,,,,,,2012-10-01T23:56:56.121700Z,NaN,NaN

In [6]:
p_picks = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'trace_p_arrival']
p_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'phase'] = "P"
p_stations = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'station_code']
p_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'phase']

/tmp/ipykernel_1648483/3861057052.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'P' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  p_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'phase'] = "P"

In [7]:
p_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'phase']

In [8]:
# print(p_picks)
# print(p_phase)
# print(p_stations)
p_phase

0      P
1      P
2      P
3      P
4      P
      ..
109    P
110    P
111    P
112    P
113    P
Name: phase, Length: 114, dtype: object

In [9]:
s_picks =  df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'trace_s_arrival']
s_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'phase'] = "S"
s_stations = df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'station_code']
s_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'phase']

In [10]:
s_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'phase']

In [11]:
s_phase

114    S
115    S
116    S
117    S
118    S
      ..
203    S
204    S
205    S
206    S
207    S
Name: phase, Length: 94, dtype: object

In [12]:
time = pd.concat(objs = [p_picks,s_picks] , axis=0)
phase = pd.concat(objs = [p_phase,s_phase] , axis=0)

In [13]:
print(time)
print(phase)

0      2012-10-01T00:04:09.141700Z
1      2012-10-01T00:36:41.601700Z
2      2012-10-01T00:55:43.061700Z
3      2012-10-01T01:16:07.681700Z
4      2012-10-01T01:41:37.561700Z
                  ...
203    2012-10-01T22:53:32.401700Z
204    2012-10-01T23:25:19.181700Z
205    2012-10-01T23:31:08.241700Z
206    2012-10-01T23:49:13.461700Z
207    2012-10-01T23:56:56.121700Z
Length: 208, dtype: object
0      P
1      P
2      P
3      P
4      P
      ..
203    S
204    S
205    S
206    S
207    S
Name: phase, Length: 208, dtype: object

In [14]:
stations = df_FS09B_20121001['station_code']
stations

0      FS09B
1      FS09B
2      FS09B
3      FS09B
4      FS09B
       ...
203    FS09B
204    FS09B
205    FS09B
206    FS09B
207    FS09B
Name: station_code, Length: 208, dtype: object

In [15]:
picks = pd.concat(objs = [stations,phase,time] , axis=1)

In [16]:
picks

    station_code phase                            0
0          FS09B     P  2012-10-01T00:04:09.141700Z
1          FS09B     P  2012-10-01T00:36:41.601700Z
2          FS09B     P  2012-10-01T00:55:43.061700Z
3          FS09B     P  2012-10-01T01:16:07.681700Z
4          FS09B     P  2012-10-01T01:41:37.561700Z
..           ...   ...                          ...
203        FS09B     S  2012-10-01T22:53:32.401700Z
204        FS09B     S  2012-10-01T23:25:19.181700Z
205        FS09B     S  2012-10-01T23:31:08.241700Z
206        FS09B     S  2012-10-01T23:49:13.461700Z
207        FS09B     S  2012-10-01T23:56:56.121700Z

[208 rows x 3 columns]

### 1.2 Concatenate data frames from several stations and format

In [6]:
csv_list = glob.glob('/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/*.csv')

In [7]:
csv_list

['/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121024.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121013.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121014.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121025.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121009.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121006.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121003.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121016.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121006.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121029.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121011.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121001.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121010.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121005.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121006.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121005.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121026.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121012.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121008.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121029.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121031.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121002.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121009.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121026.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121020.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121020.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121016.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121011.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121031.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121027.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121001.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121014.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121028.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121004.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121003.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121027.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121024.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121003.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121009.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121016.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121009.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121008.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121013.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121012.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121028.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121029.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121021.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121005.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121026.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121021.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121031.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121012.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121031.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121002.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121008.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121031.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121005.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121016.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121027.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121021.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121021.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121011.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121029.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121008.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121004.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121015.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121016.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121009.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121029.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121004.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121013.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121009.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121019.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121015.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121025.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121025.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121029.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121031.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121002.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121020.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121003.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121004.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121015.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121001.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121012.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121005.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121021.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121006.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121015.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121031.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121027.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121010.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121026.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121004.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121006.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121016.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121026.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121001.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121015.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121002.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121024.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121014.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121024.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121002.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121024.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121005.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G17B_20121012.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121024.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121014.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121005.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121012.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121010.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121024.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121013.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121023.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121009.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121015.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121025.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121028.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J25B_20121022.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121008.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121005.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121029.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121010.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121001.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121003.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121023.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121009.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121002.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121026.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121028.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS16B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121014.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121016.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121021.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS20B_20121020.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G26B_20121023.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121003.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121013.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121010.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121014.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121023.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121020.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121030.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121018.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121031.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121020.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121020.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121025.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121021.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J33B_20121027.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M09B_20121007.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS13B_20121017.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS17B_20121024.csv',
 '/home/hbito/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121007.csv',

In [23]:
df_FS09B_20121014 = pd.read_csv('~/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/FS09B_20121014.csv', index_col=0)
df_G10B_20121014 = pd.read_csv('~/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G10B_20121014.csv', index_col=0)
df_G19B_20121014 = pd.read_csv('~/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G19B_20121014.csv', index_col=0)
df_G25B_20121014 = pd.read_csv('~/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G25B_20121014.csv', index_col=0)
df_G27B_20121014 = pd.read_csv('~/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/G27B_20121014.csv', index_col=0)
df_J09B_20121014 = pd.read_csv('~/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/J09B_20121014.csv', index_col=0)
df_M12B_20121014 = pd.read_csv('~/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M12B_20121014.csv', index_col=0)
df_M14B_20121014 = pd.read_csv('~/notebooks/data/catalogs_elep_filtered_stations_20121001_to_20121031/M14B_20121014.csv', index_col=0)

In [24]:
df = pd.concat(objs = [df_FS09B_20121014,df_G10B_20121014,df_G19B_20121014,df_G25B_20121014,df_G27B_20121014,df_J09B_20121014,df_M12B_20121014,df_M14B_20121014] , axis=0)
df = df.reset_index()
df

,index,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival
0,0,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-14T00:00:00.014700Z,,,,,,NaN,2012-10-14T00:05:57.814700Z
1,1,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-14T00:00:00.014700Z,,,,,,NaN,2012-10-14T00:26:31.574700Z
2,2,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-14T00:00:00.014700Z,,,,,,NaN,2012-10-14T00:37:17.174700Z
3,3,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-14T00:00:00.014700Z,,,,,,NaN,2012-10-14T00:39:52.134700Z
4,4,,,7D,,FS09B,NaN,40.438702,-124.808502,-2161.0,,50.0,2012-10-14T00:00:00.014700Z,,,,,,NaN,2012-10-14T00:47:23.734700Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2067,290,,,7D,,M14B,NaN,40.985001,-124.589699,-638.0,,50.0,2012-10-14T00:00:00.009869Z,,,,,,2012-10-14T22:24:36.789869Z,NaN
2068,291,,,7D,,M14B,NaN,40.985001,-124.589699,-638.0,,50.0,2012-10-14T00:00:00.009869Z,,,,,,2012-10-14T22:26:19.909869Z,NaN
2069,292,,,7D,,M14B,NaN,40.985001,-124.589699,-638.0,,50.0,2012-10-14T00:00:00.009869Z,,,,,,2012-10-14T23:29:58.769869Z,NaN
2070,293,,,7D,,M14B,NaN,40.985001,-124.589699,-638.0,,50.0,2012-10-14T00:00:00.009869Z,,,,,,2012-10-14T23:32:10.929869Z,NaN
2071,294,,,7D,,M14B,NaN,40.985001,-124.589699,-638.0,,50.0,2012-10-14T00:00:00.009869Z,,,,,,2012-10-14T23:38:56.349869Z,NaN

In [8]:
all_csv =[]


for i in csv_list:
    temp = pd.read_csv(i,index_col=0)
    all_csv.append(temp)
    
df = pd.concat(all_csv, axis=0)

In [9]:
df

,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival
0,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:09:55.715136Z
1,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:12:51.771147Z
2,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:26:45.523198Z
3,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:27:47.283202Z
4,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:27:55.491202Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:54:52.278100Z,NaN
1010,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:56:37.470100Z,NaN
1011,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:57:35.558100Z,NaN
1012,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:57:53.390100Z,NaN
1013,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:58:30.254100Z,NaN

In [25]:
len(df)

2072

In [26]:
# p_picks = df.loc[df['trace_p_arrival'].notna(), 'trace_p_arrival']
# p_phase = df.loc[df['trace_p_arrival'].notna(), 'phase'] = "P"
# p_stations = df.loc[df['trace_p_arrival'].notna(), 'station_code']
# p_phase = df.loc[df['trace_p_arrival'].notna(), 'phase']

In [27]:
# p_picks

In [28]:
# p_stations

In [29]:
# # Check if the order of the picks and stations for P phase are not swapped
# df.loc[1984:1988]

In [10]:
p_phase = df.loc[df['trace_p_arrival'].notna(), 'phase'] = "P"

In [11]:
# Notice that "P" is assigned in the phase column only for P picks
df

,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival,phase
0,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:09:55.715136Z,P
1,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:12:51.771147Z,P
2,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:26:45.523198Z,P
3,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:27:47.283202Z,P
4,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:27:55.491202Z,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:54:52.278100Z,NaN,n
1010,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:56:37.470100Z,NaN,n
1011,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:57:35.558100Z,NaN,n
1012,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:57:53.390100Z,NaN,n
1013,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:58:30.254100Z,NaN,n

In [12]:
p_stas_picks_phase = df.loc[df['trace_p_arrival'].notna(), ['station_code','trace_p_arrival','phase']]
# p_stations = df.loc[df['trace_p_arrival'].notna(), 'station_code']
# p_phase = df.loc[df['trace_p_arrival'].notna(), 'phase']
p_stas_picks_phase

    station_code              trace_p_arrival phase
0           G26B  2012-10-24T00:09:55.715136Z     P
1           G26B  2012-10-24T00:12:51.771147Z     P
2           G26B  2012-10-24T00:26:45.523198Z     P
3           G26B  2012-10-24T00:27:47.283202Z     P
4           G26B  2012-10-24T00:27:55.491202Z     P
..           ...                          ...   ...
477         M09B  2012-10-20T23:47:42.174100Z     P
478         M09B  2012-10-20T23:48:04.774100Z     P
479         M09B  2012-10-20T23:51:08.430100Z     P
480         M09B  2012-10-20T23:52:22.750100Z     P
481         M09B  2012-10-20T23:52:32.574100Z     P

[146940 rows x 3 columns]

In [13]:
_p_stas_picks_phase = p_stas_picks_phase.rename(columns={"station_code": "station", "trace_p_arrival": "time"})
_p_stas_picks_phase

    station                         time phase
0      G26B  2012-10-24T00:09:55.715136Z     P
1      G26B  2012-10-24T00:12:51.771147Z     P
2      G26B  2012-10-24T00:26:45.523198Z     P
3      G26B  2012-10-24T00:27:47.283202Z     P
4      G26B  2012-10-24T00:27:55.491202Z     P
..      ...                          ...   ...
477    M09B  2012-10-20T23:47:42.174100Z     P
478    M09B  2012-10-20T23:48:04.774100Z     P
479    M09B  2012-10-20T23:51:08.430100Z     P
480    M09B  2012-10-20T23:52:22.750100Z     P
481    M09B  2012-10-20T23:52:32.574100Z     P

[146940 rows x 3 columns]

In [34]:
# s_picks =  df.loc[df['trace_s_arrival'].notna(), 'trace_s_arrival']
# s_phase = df.loc[df['trace_s_arrival'].notna(), 'phase'] = "S"
# s_stations = df.loc[df['trace_s_arrival'].notna(), 'station_code']
# s_phase = df.loc[df['trace_s_arrival'].notna(), 'phase']

In [35]:
# s_picks

In [36]:
# s_stations

In [37]:
# # Check if the order of the picks and stations for S picks are not swapped
# df.loc[183:187]

In [38]:
# Check if the order of the stations are not swapped

In [39]:
# print(len(p_phase)+len(s_phase))

In [14]:
s_phase = df.loc[df['trace_s_arrival'].notna(), 'phase'] = "S"

In [15]:
# Check if S is assigned to the appropriate rows
df

,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival,phase
0,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:09:55.715136Z,P
1,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:12:51.771147Z,P
2,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:26:45.523198Z,P
3,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:27:47.283202Z,P
4,,,7D,,G26B,NaN,41.924900,-125.177498,-2357.0,,124.999992,2012-10-24T00:00:00.003100Z,,,,,,NaN,2012-10-24T00:27:55.491202Z,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:54:52.278100Z,NaN,S
1010,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:56:37.470100Z,NaN,S
1011,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:57:35.558100Z,NaN,S
1012,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:57:53.390100Z,NaN,S
1013,,,7D,,M09B,NaN,44.249699,-125.058899,-914.0,,125.000000,2012-10-20T00:00:00.006100Z,,,,,,2012-10-20T23:58:30.254100Z,NaN,S

In [16]:
s_stas_picks_phase = df.loc[df['trace_s_arrival'].notna(), ['station_code','trace_s_arrival','phase']]
# p_stations = df.loc[df['trace_p_arrival'].notna(), 'station_code']
# p_phase = df.loc[df['trace_p_arrival'].notna(), 'phase']
s_stas_picks_phase

     station_code              trace_s_arrival phase
215          G26B  2012-10-24T00:09:55.763136Z     S
216          G26B  2012-10-24T00:12:59.419148Z     S
217          G26B  2012-10-24T00:27:06.195199Z     S
218          G26B  2012-10-24T00:27:47.427202Z     S
219          G26B  2012-10-24T00:27:56.427202Z     S
...           ...                          ...   ...
1009         M09B  2012-10-20T23:54:52.278100Z     S
1010         M09B  2012-10-20T23:56:37.470100Z     S
1011         M09B  2012-10-20T23:57:35.558100Z     S
1012         M09B  2012-10-20T23:57:53.390100Z     S
1013         M09B  2012-10-20T23:58:30.254100Z     S

[124001 rows x 3 columns]

In [17]:
_s_stas_picks_phase = s_stas_picks_phase.rename(columns={"station_code": "station", "trace_s_arrival": "time"})
_s_stas_picks_phase

     station                         time phase
215     G26B  2012-10-24T00:09:55.763136Z     S
216     G26B  2012-10-24T00:12:59.419148Z     S
217     G26B  2012-10-24T00:27:06.195199Z     S
218     G26B  2012-10-24T00:27:47.427202Z     S
219     G26B  2012-10-24T00:27:56.427202Z     S
...      ...                          ...   ...
1009    M09B  2012-10-20T23:54:52.278100Z     S
1010    M09B  2012-10-20T23:56:37.470100Z     S
1011    M09B  2012-10-20T23:57:35.558100Z     S
1012    M09B  2012-10-20T23:57:53.390100Z     S
1013    M09B  2012-10-20T23:58:30.254100Z     S

[124001 rows x 3 columns]

In [18]:
picks = pd.concat(objs = [_p_stas_picks_phase,_s_stas_picks_phase] , axis=0)
picks

     station                         time phase
0       G26B  2012-10-24T00:09:55.715136Z     P
1       G26B  2012-10-24T00:12:51.771147Z     P
2       G26B  2012-10-24T00:26:45.523198Z     P
3       G26B  2012-10-24T00:27:47.283202Z     P
4       G26B  2012-10-24T00:27:55.491202Z     P
...      ...                          ...   ...
1009    M09B  2012-10-20T23:54:52.278100Z     S
1010    M09B  2012-10-20T23:56:37.470100Z     S
1011    M09B  2012-10-20T23:57:35.558100Z     S
1012    M09B  2012-10-20T23:57:53.390100Z     S
1013    M09B  2012-10-20T23:58:30.254100Z     S

[270941 rows x 3 columns]

In [19]:
# Swap the time and phase columns
picks = picks.iloc[:,[0,2,1]]
picks

     station phase                         time
0       G26B     P  2012-10-24T00:09:55.715136Z
1       G26B     P  2012-10-24T00:12:51.771147Z
2       G26B     P  2012-10-24T00:26:45.523198Z
3       G26B     P  2012-10-24T00:27:47.283202Z
4       G26B     P  2012-10-24T00:27:55.491202Z
...      ...   ...                          ...
1009    M09B     S  2012-10-20T23:54:52.278100Z
1010    M09B     S  2012-10-20T23:56:37.470100Z
1011    M09B     S  2012-10-20T23:57:35.558100Z
1012    M09B     S  2012-10-20T23:57:53.390100Z
1013    M09B     S  2012-10-20T23:58:30.254100Z

[270941 rows x 3 columns]

In [20]:
picks.to_csv("~/notebooks/src/workflow/data/picks_20121014.csv")

In [22]:
time = pd.Series(pd.concat(objs = [p_picks,s_picks] , axis=0), name='time')
# phase = pd.Series(pd.concat(objs = [p_phase,s_phase] , axis=0),name='phase')

NameError: name 'p_picks' is not defined

In [21]:
time

CPU times: user 2 µs, sys: 5 µs, total: 7 µs
Wall time: 12.6 µs

In [58]:
# type(time)

In [59]:
# stations = pd.Series(df['station_code'],name='station')

In [60]:
# picks = pd.concat(objs = [stations,phase,time] , axis=1)
# picks

In [61]:
# picks.iloc[1224]

In [62]:
# 2448/2

In [63]:
# picks.to_csv("~/elep-test/surface_events/data/phase_association/picks")

## 2. Format data frames for stations
This section is not necessary anymore

In [23]:
row_FS09B_20121001 = df_FS09B_20121001.iloc[0]
row_FS09B_20121001

NameError: name 'df_FS09B_20121001' is not defined

In [65]:
_row_FS09B_20121001 = row_FS09B_20121001.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]

In [66]:
_row_FS09B_20121001

station_code                  FS09B
station_longitude_deg   -124.808502
station_latitude_deg      40.438702
station_elevation_m         -2161.0
Name: 0, dtype: object

In [67]:
row_FS09B_20121014 = df_FS09B_20121014.iloc[0]
# row_FS13B_20121006 =df_FS13B_20121006.iloc[0]
row_G10B_20121014 =df_G10B_20121014.iloc[0]
row_G19B_20121014=df_G19B_20121014.iloc[0]
row_G25B_20121014 =df_G25B_20121014.iloc[0]
row_G27B_20121014 =df_G27B_20121014.iloc[0]
row_J09B_20121014 =df_J09B_20121014.iloc[0]
row_M12B_20121014 =df_M12B_20121014.iloc[0]
row_M14B_20121014 =df_M14B_20121014.iloc[0]

In [68]:
_row_FS09B_20121014 = row_FS09B_20121014.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]
# _row_FS13B_20121014  = row_FS13B_20121014 .loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]
_row_G10B_20121014 = row_G10B_20121014.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]
_row_G19B_20121014 = row_G19B_20121014.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]
_row_G25B_20121014 = row_G25B_20121014.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]
_row_G27B_20121014 = row_G27B_20121014.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]
_row_J09B_20121014 = row_J09B_20121014.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]
_row_M12B_20121014 = row_M12B_20121014.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]
_row_M14B_20121014 = row_M14B_20121014.loc[['station_code','station_longitude_deg','station_latitude_deg','station_elevation_m']]

In [69]:
_row_FS09B_20121014  = pd.DataFrame(np.array(_row_FS09B_20121014).reshape(1,len(_row_FS09B_20121014)))
# _row_FS13B_20121006  = pd.DataFrame(np.array(_row_FS13B_20121006).reshape(1,len(_row_FS13B_20121006)))
_row_G10B_20121014 = pd.DataFrame(np.array(_row_G10B_20121014).reshape(1,len(_row_G10B_20121014)))
_row_G19B_20121014 = pd.DataFrame(np.array(_row_G19B_20121014).reshape(1,len(_row_G19B_20121014)))
_row_G25B_20121014 = pd.DataFrame(np.array(_row_G25B_20121014).reshape(1,len(_row_G25B_20121014)))
_row_G27B_20121014 = pd.DataFrame(np.array(_row_G27B_20121014).reshape(1,len(_row_G27B_20121014)))
_row_J09B_20121014 = pd.DataFrame(np.array(_row_J09B_20121014).reshape(1,len(_row_J09B_20121014)))
_row_M12B_20121014= pd.DataFrame(np.array(_row_M12B_20121014).reshape(1,len(_row_M12B_20121014)))
_row_M14B_20121014 = pd.DataFrame(np.array(_row_M14B_20121014).reshape(1,len(_row_M14B_20121014)))

In [70]:
stations = pd.concat(objs = [_row_FS09B_20121014,_row_G10B_20121014,_row_G19B_20121014,_row_G25B_20121014,_row_G27B_20121014,_row_J09B_20121014,_row_M12B_20121014,_row_M14B_20121014] , axis=0, ignore_index=True)
stations

       0           1          2       3
0  FS09B -124.808502  40.438702 -2161.0
1   G10B -125.553299  40.677898 -2936.0
2   G19B -125.773598    41.3074 -3071.0
3   G25B -124.586098  41.919899  -430.0
4   G27B -126.016701  41.916599 -3480.0
5   J09B -124.726997  43.151001  -252.0
6   M12B -124.946098  42.183998 -1045.0
7   M14B -124.589699  40.985001  -638.0

In [71]:
_stations = stations.rename(columns={0: 'id',1: 'longitude',2: 'latitude',3: 'elevation'})
_stations

      id   longitude   latitude elevation
0  FS09B -124.808502  40.438702   -2161.0
1   G10B -125.553299  40.677898   -2936.0
2   G19B -125.773598    41.3074   -3071.0
3   G25B -124.586098  41.919899    -430.0
4   G27B -126.016701  41.916599   -3480.0
5   J09B -124.726997  43.151001    -252.0
6   M12B -124.946098  42.183998   -1045.0
7   M14B -124.589699  40.985001    -638.0

In [72]:
_stations.to_csv("~/notebooks/src/workflow/data/stations_20121014.csv")