## Notebook for formatting data frames for phase association

In [4]:
import pandas as pd
import numpy as np
import datetime
import glob
import os

In [2]:
# Make a directory to store the data associated with the picks
year =2012
filepath = f'../../data/datasets_{year}'
os.makedirs(filepath,exist_ok=True)

### 1.1 Load the station data frame

In [5]:
stas_2011 = pd.read_csv('../data/datasets_2011/stas_2011_pnsn_wa.csv',index_col=0)
stas_2012 = pd.read_csv('../data/datasets_2012/stas_2012_pnsn_wa.csv',index_col=0)
stas_2013 = pd.read_csv('../data/datasets_2013/stas_2013_pnsn_wa.csv',index_col=0)
stas_2014 = pd.read_csv('../data/datasets_2014/stas_2014_pnsn_wa.csv',index_col=0)
stas_2015 = pd.read_csv('../data/datasets_2015/stas_2015_pnsn_wa.csv',index_col=0)
print(stas_2011)
print(stas_2012)
print(stas_2013)
print(stas_2014)
print(stas_2015)

          id   longitude   latitude  elevation
0    CN.LZB. -123.824000  48.612200      794.0
1   TA.G03D. -123.264099  45.211498      222.0
2   UW.LRIV. -123.504000  48.057500      293.8
3   UW.LEBA. -123.563202  46.545898       78.6
4   UW.WISH. -123.771180  47.116980       45.0
5    CN.PGC. -123.452100  48.649800       12.0
6    CN.SHB. -123.877100  49.598500     1129.0
7    UW.SQM. -123.048058  48.073681       45.0
8    CN.SNB. -123.172300  48.775100      402.0
9    UW.OFR. -124.396042  47.933128      152.0
10  CN.NLLB. -123.988200  49.227100      199.0
11   CN.OZB. -125.497800  48.961200      626.0
12   CN.PFB. -124.454100  48.574700      449.0
13   CN.VGZ. -123.325100  48.413100       67.0
14  CN.BMSB. -125.135500  48.835600       10.0
15  TA.D03D. -123.089401  47.534698      262.0
16  UW.FISH. -123.559100  45.930600      327.0
17  UW.HEBO. -123.755386  45.213501      875.0
18   CN.BTB. -125.522600  49.468600     1607.0
19  UW.RADR. -123.798970  46.421810      591.4
20  UW.MEGW. -123.877090  46.266090      351.0
21  TA.F04D. -123.010803  46.082901      236.0
          id   longitude   latitude  elevation
0    CN.PGC. -123.452100  48.649800       12.0
1    CN.VGZ. -123.325100  48.413100       67.0
2   UW.LEBA. -123.563202  46.545898       78.6
3    CN.PFB. -124.454100  48.574700      449.0
4    CN.OZB. -125.497800  48.961200      626.0
5    CN.SHB. -123.877100  49.598500     1129.0
6    CN.LZB. -123.824000  48.612200      794.0
7   TA.D03D. -123.089401  47.534698      262.0
8   UW.HEBO. -123.755386  45.213501      875.0
9   TA.F04D. -123.010803  46.082901      236.0
10  UW.MEGW. -123.877090  46.266090      351.0
11  CN.NLLB. -123.988200  49.227100      199.0
12  UW.RADR. -123.798970  46.421810      591.4
13   UW.OFR. -124.396042  47.933128      152.0
14  TA.G03D. -123.264099  45.211498      222.0
15  UW.LRIV. -123.504000  48.057500      293.8
16  UW.WISH. -123.771180  47.116980       45.0
17  UW.FISH. -123.559100  45.930600      327.0
18   CN.BTB. -125.522600  49.468600     1607.0
19   CN.SNB. -123.172300  48.775100      402.0
          id   longitude   latitude  elevation
0   UW.LEBA. -123.563202  46.545898       78.6
1    CN.PGC. -123.452100  48.649800       12.0
2   TA.G03D. -123.264099  45.211498      222.0
3   TA.F04D. -123.010803  46.082901      236.0
4   UW.WISH. -123.771180  47.116980       45.0
5    CN.SHB. -123.877100  49.598500     1129.0
6   TA.D03D. -123.089401  47.534698      262.0
7    CN.PFB. -124.454100  48.574700      449.0
8   UW.HEBO. -123.755386  45.213501      875.0
9    CN.SNB. -123.172300  48.775100      402.0
10  UW.LRIV. -123.504000  48.057500      293.8
11  UW.RADR. -123.798970  46.421810      591.4
12   CN.OZB. -125.497800  48.961200      626.0
13  CN.NLLB. -123.988200  49.227100      199.0
14   CN.VGZ. -123.325100  48.413100       67.0
15   CN.LZB. -123.824000  48.612200      794.0
16   CN.BTB. -125.522600  49.468600     1607.0
17  UW.FISH. -123.559100  45.930600      327.0
18  CN.BFSB. -125.136000  48.833600       33.0
19   UW.OFR. -124.396042  47.933128      152.0
          id   longitude   latitude  elevation
0   TA.D03D. -123.089401  47.534698      262.0
1    CN.VGZ. -123.325100  48.413100       67.0
2   CN.NLLB. -123.988200  49.227100      199.0
3   UW.LRIV. -123.504000  48.057500      293.8
4   UW.HEBO. -123.755386  45.213501      875.0
5    CN.LZB. -123.824000  48.612200      794.0
6   UW.FISH. -123.559100  45.930600      327.0
7    CN.PFB. -124.454100  48.574700      449.0
8   UW.WISH. -123.771180  47.116980       45.0
9   TA.F04D. -123.010803  46.082901      236.0
10  TA.G03D. -123.264099  45.211498      222.0
11   CN.SNB. -123.172300  48.775100      402.0
12   CN.SHB. -123.877100  49.598500     1129.0
13   CN.OZB. -125.497800  48.961200      626.0
14   CN.PGC. -123.452100  48.649800       12.0
15   CN.BTB. -125.522600  49.468600     1607.0
16  CN.BFSB. -125.136000  48.833600       33.0
17  UW.RADR. -123.798970  46.421810      591.4
18  CN.CLRS. -124.130900  48.820300      174.0
          id   longitude   latitude  elevation
0   UW.WISH. -123.771180  47.116980       45.0
1   CN.CLRS. -124.130900  48.820300      174.0
2   C8.TOFB. -125.907800  49.154300       13.0
3   C8.PA12. -123.449600  48.648200       10.0
4    CN.SNB. -123.172300  48.775100      402.0
5   CN.BFSB. -125.136000  48.833600       33.0
6   UW.HEBO. -123.755386  45.213501      875.0
7    CN.PFB. -124.454100  48.574700      449.0
8   C8.PA01. -123.447000  48.652600        3.0
9   TA.F04D. -123.010803  46.082901      236.0
10  C8.PA05. -123.443800  48.649700        8.0
11  UW.RADR. -123.798970  46.421810      591.4
12  C8.PA02. -123.448900  48.651800        3.0
13   CN.PGC. -123.452100  48.649800       12.0
14  CN.NLLB. -123.988200  49.227100      199.0
15  TA.G03D. -123.264099  45.211498      222.0
16  C8.MWAB. -125.303200  49.741100     1176.0
17   CN.SHB. -123.877100  49.598500     1129.0
18  C8.SPLB. -125.652600  49.892100      276.0
19   CN.OZB. -125.497800  48.961200      626.0
20  TA.D03D. -123.089401  47.534698      262.0
21   CN.VGZ. -123.325100  48.413100       67.0
22   CN.BTB. -125.522600  49.468600     1607.0
23  UW.LRIV. -123.504000  48.057500      293.8
24  C8.SOKB. -123.673100  48.394700       45.0
25  UW.FISH. -123.559100  45.930600      327.0

In [6]:
stas = pd.concat([stas_2011,stas_2012,stas_2013,
                           stas_2014,stas_2015],ignore_index=True)
stas = stas.drop_duplicates(subset='id')
stas

           id   longitude   latitude  elevation
0     CN.LZB. -123.824000  48.612200      794.0
1    TA.G03D. -123.264099  45.211498      222.0
2    UW.LRIV. -123.504000  48.057500      293.8
3    UW.LEBA. -123.563202  46.545898       78.6
4    UW.WISH. -123.771180  47.116980       45.0
5     CN.PGC. -123.452100  48.649800       12.0
6     CN.SHB. -123.877100  49.598500     1129.0
7     UW.SQM. -123.048058  48.073681       45.0
8     CN.SNB. -123.172300  48.775100      402.0
9     UW.OFR. -124.396042  47.933128      152.0
10   CN.NLLB. -123.988200  49.227100      199.0
11    CN.OZB. -125.497800  48.961200      626.0
12    CN.PFB. -124.454100  48.574700      449.0
13    CN.VGZ. -123.325100  48.413100       67.0
14   CN.BMSB. -125.135500  48.835600       10.0
15   TA.D03D. -123.089401  47.534698      262.0
16   UW.FISH. -123.559100  45.930600      327.0
17   UW.HEBO. -123.755386  45.213501      875.0
18    CN.BTB. -125.522600  49.468600     1607.0
19   UW.RADR. -123.798970  46.421810      591.4
20   UW.MEGW. -123.877090  46.266090      351.0
21   TA.F04D. -123.010803  46.082901      236.0
60   CN.BFSB. -125.136000  48.833600       33.0
80   CN.CLRS. -124.130900  48.820300      174.0
83   C8.TOFB. -125.907800  49.154300       13.0
84   C8.PA12. -123.449600  48.648200       10.0
89   C8.PA01. -123.447000  48.652600        3.0
91   C8.PA05. -123.443800  48.649700        8.0
93   C8.PA02. -123.448900  48.651800        3.0
97   C8.MWAB. -125.303200  49.741100     1176.0
99   C8.SPLB. -125.652600  49.892100      276.0
105  C8.SOKB. -123.673100  48.394700       45.0

In [7]:
# Create  a csv file
stas.to_csv('../data/datasets_pnsn_wa/all_stations_pnsn_wa.csv')

### 1.2 Concatenate data frames from several stations and format

In [5]:
# Gather all the files that we produced in 1_parallel_detect_picks_elep_all_sta
csv_list = glob.glob('../../data/picks_201*/*.csv')

In [6]:
# Print csv_list
csv_list

['../../data/picks_20120101/BABR_20120101.csv',
 '../../data/picks_20120101/LEBA_20120101.csv',
 '../../data/picks_20120101/DBO_20120101.csv',
 '../../data/picks_20120101/L02D_20120101.csv',
 '../../data/picks_20120101/KSXB_20120101.csv',
 '../../data/picks_20120101/KCT_20120101.csv',
 '../../data/picks_20120101/FN07A_20120101.csv',
 '../../data/picks_20120101/NLLB_20120101.csv',
 '../../data/picks_20120101/FN08A_20120101.csv',
 '../../data/picks_20120101/FN18A_20120101.csv',
 '../../data/picks_20120101/G03D_20120101.csv',
 '../../data/picks_20120101/SHB_20120101.csv',
 '../../data/picks_20120101/J34A_20120101.csv',
 '../../data/picks_20120101/J73A_20120101.csv',
 '../../data/picks_20120101/FN01A_20120101.csv',
 '../../data/picks_20120101/M07A_20120101.csv',
 '../../data/picks_20120101/I02D_20120101.csv',
 '../../data/picks_20120101/J57A_20120101.csv',
 '../../data/picks_20120101/I03D_20120101.csv',
 '../../data/picks_20120101/LRIV_20120101.csv',
 '../../data/picks_20120101/J33A_20120101.csv',
 '../../data/picks_20120101/M06A_20120101.csv',
 '../../data/picks_20120101/PGC_20120101.csv',
 '../../data/picks_20120101/RADR_20120101.csv',
 '../../data/picks_20120101/KRMB_20120101.csv',
 '../../data/picks_20120101/M08A_20120101.csv',
 '../../data/picks_20120101/J25A_20120101.csv',
 '../../data/picks_20120101/KHMB_20120101.csv',
 '../../data/picks_20120101/LZB_20120101.csv',
 '../../data/picks_20120101/KHBB_20120101.csv',
 '../../data/picks_20120101/MEGW_20120101.csv',
 '../../data/picks_20120101/TAKO_20120101.csv',
 '../../data/picks_20120101/FN12A_20120101.csv',
 '../../data/picks_20120101/J58A_20120101.csv',
 '../../data/picks_20120101/YOUB_20120101.csv',
 '../../data/picks_20120101/JEDS_20120101.csv',
 '../../data/picks_20120101/J26A_20120101.csv',
 '../../data/picks_20120101/M03A_20120101.csv',
 '../../data/picks_20120101/J41A_20120101.csv',
 '../../data/picks_20120101/OFR_20120101.csv',
 '../../data/picks_20120101/M01A_20120101.csv',
 '../../data/picks_20120101/KMPB_20120101.csv',
 '../../data/picks_20120101/J59A_20120101.csv',
 '../../data/picks_20120101/J65A_20120101.csv',
 '../../data/picks_20120101/K02D_20120101.csv',
 '../../data/picks_20120101/J51A_20120101.csv',
 '../../data/picks_20120101/KMR_20120101.csv',
 '../../data/picks_20120101/J01D_20120101.csv',
 '../../data/picks_20120101/HEBO_20120101.csv',
 '../../data/picks_20120101/J50A_20120101.csv',
 '../../data/picks_20120101/VGZ_20120101.csv',
 '../../data/picks_20120101/KEB_20120101.csv',
 '../../data/picks_20120101/G03A_20120101.csv',
 '../../data/picks_20120101/M02A_20120101.csv',
 '../../data/picks_20120101/KBO_20120101.csv',
 '../../data/picks_20120101/OZB_20120101.csv',
 '../../data/picks_20120101/J49A_20120101.csv',
 '../../data/picks_20120101/J42A_20120101.csv',
 '../../data/picks_20120101/FISH_20120101.csv',
 '../../data/picks_20120101/FN14A_20120101.csv',
 '../../data/picks_20120101/FN16A_20120101.csv',
 '../../data/picks_20120101/JCC_20120101.csv',
 '../../data/picks_20120101/F04D_20120101.csv',
 '../../data/picks_20120101/J35A_20120101.csv',
 '../../data/picks_20120101/KRP_20120101.csv',
 '../../data/picks_20120101/D03D_20120101.csv',
 '../../data/picks_20120101/J43A_20120101.csv',
 '../../data/picks_20120101/FN05A_20120101.csv',
 '../../data/picks_2012/PGC_20120125.csv',
 '../../data/picks_2012/KSXB_20120105.csv',
 '../../data/picks_2012/JCC_20120213.csv',
 '../../data/picks_2012/VGZ_20120203.csv',
 '../../data/picks_2012/J01D_20120701.csv',
 '../../data/picks_2012/LEBA_20120209.csv',
 '../../data/picks_2012/FS02B_20121216.csv',
 '../../data/picks_2012/J01D_20120216.csv',
 '../../data/picks_2012/LEBA_20120906.csv',
 '../../data/picks_2012/KHBB_20120312.csv',
 '../../data/picks_2012/G25B_20121220.csv',
 '../../data/picks_2012/MGB_20120216.csv',
 '../../data/picks_2012/J50A_20120510.csv',
 '../../data/picks_2012/FN14A_20120614.csv',
 '../../data/picks_2012/PFB_20121101.csv',
 '../../data/picks_2012/KCT_20120303.csv',
 '../../data/picks_2012/KBO_20120301.csv',
 '../../data/picks_2012/OZB_20120203.csv',
 '../../data/picks_2012/J01D_20120530.csv',
 '../../data/picks_2012/J51A_20120227.csv',
 '../../data/picks_2012/SHB_20120515.csv',
 '../../data/picks_2012/DBO_20121101.csv',
 '../../data/picks_2012/FS18B_20121105.csv',
 '../../data/picks_2012/LZB_20121122.csv',
 '../../data/picks_2012/L02E_20121103.csv',
 '../../data/picks_2012/FS06B_20121009.csv',
 '../../data/picks_2012/J51A_20120331.csv',
 '../../data/picks_2012/J25A_20120409.csv',
 '../../data/picks_2012/KEB_20120104.csv',
 '../../data/picks_2012/FN01A_20120608.csv',
 '../../data/picks_2012/LZB_20120604.csv',
 '../../data/picks_2012/KHBB_20120402.csv',
 '../../data/picks_2012/FS08B_20121002.csv',
 '../../data/picks_2012/G11B_20121031.csv',
 '../../data/picks_2012/FN16A_20120216.csv',
 '../../data/picks_2012/G33B_20121201.csv',
 '../../data/picks_2012/M11B_20120918.csv',
 '../../data/picks_2012/M03A_20120613.csv',
 '../../data/picks_2012/FN07A_20120421.csv',
 '../../data/picks_2012/FS02B_20121224.csv',
 '../../data/picks_2012/SHB_20120917.csv',
 '../../data/picks_2012/FS09B_20121111.csv',
 '../../data/picks_2012/FN12A_20120228.csv',
 '../../data/picks_2012/D03D_20120821.csv',
 '../../data/picks_2012/HEBO_20120807.csv',
 '../../data/picks_2012/D03D_20120210.csv',
 '../../data/picks_2012/DBO_20120510.csv',
 '../../data/picks_2012/FN07A_20120317.csv',
 '../../data/picks_2012/FS02B_20121110.csv',
 '../../data/picks_2012/KRP_20120211.csv',
 '../../data/picks_2012/KHBB_20120714.csv',
 '../../data/picks_2012/J09B_20120907.csv',
 '../../data/picks_2012/F04D_20120923.csv',
 '../../data/picks_2012/KSXB_20120721.csv',
 '../../data/picks_2012/VGZ_20120808.csv',
 '../../data/picks_2012/J59A_20120426.csv',
 '../../data/picks_2012/I02D_20120709.csv',
 '../../data/picks_2012/TAKO_20120419.csv',
 '../../data/picks_2012/J01D_20120927.csv',
 '../../data/picks_2012/PGC_20120803.csv',
 '../../data/picks_2012/J42A_20120315.csv',
 '../../data/picks_2012/MEGW_20120108.csv',
 '../../data/picks_2012/FS13B_20121105.csv',
 '../../data/picks_2012/G34B_20121201.csv',
 '../../data/picks_2012/FS01B_20121205.csv',
 '../../data/picks_2012/KRMB_20120119.csv',
 '../../data/picks_2012/NLLB_20121008.csv',
 '../../data/picks_2012/KSXB_20120309.csv',
 '../../data/picks_2012/TAKO_20120818.csv',
 '../../data/picks_2012/KMPB_20120716.csv',
 '../../data/picks_2012/DBO_20120928.csv',
 '../../data/picks_2012/PGC_20121216.csv',
 '../../data/picks_2012/FS15B_20121227.csv',
 '../../data/picks_2012/KRP_20120828.csv',
 '../../data/picks_2012/F04D_20120115.csv',
 '../../data/picks_2012/FN12A_20120209.csv',
 '../../data/picks_2012/HEBO_20120207.csv',
 '../../data/picks_2012/J57A_20120130.csv',
 '../../data/picks_2012/KHMB_20121122.csv',
 '../../data/picks_2012/F04D_20120206.csv',
 '../../data/picks_2012/FS19B_20121125.csv',
 '../../data/picks_2012/J41A_20120502.csv',
 '../../data/picks_2012/LEBA_20120818.csv',
 '../../data/picks_2012/KRP_20120319.csv',
 '../../data/picks_2012/L02E_20121107.csv',
 '../../data/picks_2012/KBO_20120328.csv',
 '../../data/picks_2012/KMPB_20120605.csv',
 '../../data/picks_2012/KEB_20120215.csv',
 '../../data/picks_2012/G19B_20121009.csv',
 '../../data/picks_2012/G33B_20121104.csv',
 '../../data/picks_2012/FS09B_20121005.csv',
 '../../data/picks_2012/JCC_20120131.csv',
 '../../data/picks_2012/RADR_20121021.csv',
 '../../data/picks_2012/LEBA_20120707.csv',
 '../../data/picks_2012/J43A_20120514.csv',
 '../../data/picks_2012/FN12A_20120531.csv',
 '../../data/picks_2012/FS06B_20121011.csv',
 '../../data/picks_2012/J49A_20120410.csv',
 '../../data/picks_2012/KEB_20120328.csv',
 '../../data/picks_2012/G26B_20121118.csv',
 '../../data/picks_2012/J51A_20120313.csv',
 '../../data/picks_2012/J25B_20121002.csv',
 '../../data/picks_2012/OFR_20120927.csv',
 '../../data/picks_2012/DBO_20120122.csv',
 '../../data/picks_2012/FS20B_20121024.csv',
 '../../data/picks_2012/J42A_20120519.csv',
 '../../data/picks_2012/G03D_20120713.csv',
 '../../data/picks_2012/DBO_20120606.csv',
 '../../data/picks_2012/KCT_20120330.csv',
 '../../data/picks_2012/LZB_20120826.csv',
 '../../data/picks_2012/KMPB_20120626.csv',
 '../../data/picks_2012/G03D_20120721.csv',
 '../../data/picks_2012/J73A_20120602.csv',
 '../../data/picks_2012/TAKO_20120621.csv',
 '../../data/picks_2012/G28B_20121201.csv',
 '../../data/picks_2012/LRIV_20121224.csv',
 '../../data/picks_2012/FORK_20120124.csv',
 '../../data/picks_2012/FS15B_20121015.csv',
 '../../data/picks_2012/K02D_20120805.csv',
 '../../data/picks_2012/FN07A_20120305.csv',
 '../../data/picks_2012/FS02B_20121115.csv',
 '../../data/picks_2012/VGZ_20120202.csv',
 '../../data/picks_2012/WISH_20120510.csv',
 '../../data/picks_2012/SHB_20120628.csv',
 '../../data/picks_2012/J17B_20120919.csv',
 '../../data/picks_2012/OZB_20120114.csv',
 '../../data/picks_2012/G02B_20120910.csv',
 '../../data/picks_2012/FORK_20121202.csv',
 '../../data/picks_2012/G11B_20120930.csv',
 '../../data/picks_2012/FS19B_20121110.csv',
 '../../data/picks_2012/FN12A_20120214.csv',
 '../../data/picks_2012/M03A_20120326.csv',
 '../../data/picks_2012/WISH_20120406.csv',
 '../../data/picks_2012/KMPB_20120312.csv',
 '../../data/picks_2012/FN07A_20120108.csv',
 '../../data/picks_2012/G10B_20121227.csv',
 '../../data/picks_2012/BB070_20121010.csv',
 '../../data/picks_2012/J50A_20120404.csv',
 '../../data/picks_2012/PGC_20120921.csv',
 '../../data/picks_2012/RADR_20120708.csv',
 '../../data/picks_2012/FISH_20120821.csv',
 '../../data/picks_2012/M08A_20120218.csv',
 '../../data/picks_2012/G10B_20121031.csv',
 '../../data/picks_2012/KEB_20121018.csv',
 '../../data/picks_2012/M08A_20120420.csv',
 '../../data/picks_2012/J33B_20121218.csv',
 '../../data/picks_2012/KMR_20121214.csv',
 '../../data/picks_2012/J34A_20120503.csv',
 '../../data/picks_2012/FS02B_20121130.csv',
 '../../data/picks_2012/FN16A_20120611.csv',
 '../../data/picks_2012/FN18A_20120516.csv',
 '../../data/picks_2012/L02D_20120220.csv',
 '../../data/picks_2012/KMPB_20120416.csv',
 '../../data/picks_2012/VGZ_20120621.csv',
 '../../data/picks_2012/JCC_20121130.csv',
 '../../data/picks_2012/J17B_20120729.csv',
 '../../data/picks_2012/M06A_20120427.csv',
 '../../data/picks_2012/G26B_20121102.csv',
 '../../data/picks_2012/FORK_20121125.csv',
 '../../data/picks_2012/RADR_20120817.csv',
 '../../data/picks_2012/FS07B_20121003.csv',
 '../../data/picks_2012/G03D_20120308.csv',
 '../../data/picks_2012/J59A_20120320.csv',
 '../../data/picks_2012/BABR_20120629.csv',
 '../../data/picks_2012/FN12A_20120520.csv',
 '../../data/picks_2012/FORK_20121122.csv',
 '../../data/picks_2012/J41A_20120120.csv',
 '../../data/picks_2012/J34A_20120712.csv',
 '../../data/picks_2012/KRP_20120401.csv',
 '../../data/picks_2012/J01D_20120828.csv',
 '../../data/picks_2012/LEBA_20120407.csv',
 '../../data/picks_2012/FN07A_20120415.csv',
 '../../data/picks_2012/FS18B_20121028.csv',
 '../../data/picks_2012/FS10B_20121220.csv',
 '../../data/picks_2012/SHB_20121219.csv',
 '../../data/picks_2012/J59A_20120229.csv',
 '../../data/picks_2012/BTB_20120922.csv',
 '../../data/picks_2012/J18B_20121225.csv',
 '../../data/picks_2012/KRP_20120425.csv',
 '../../data/picks_2012/NLLB_20120208.csv',
 '../../data/picks_2012/J01D_20120727.csv',
 '../../data/picks_2012/M14B_20121230.csv',
 '../../data/picks_2012/I02D_20120413.csv',
 '../../data/picks_2012/J19B_20121208.csv',
 '../../data/picks_2012/KMPB_20120612.csv',
 '../../data/picks_2012/J42A_20120702.csv',
 '../../data/picks_2012/FN08A_20120525.csv',
 '../../data/picks_2012/MEGW_20120204.csv',
 '../../data/picks_2012/G02B_20121231.csv',
 '../../data/picks_2012/VGZ_20120809.csv',
 '../../data/picks_2012/FN01A_20120317.csv',
 '../../data/picks_2012/KMR_20120921.csv',
 '../../data/picks_2012/M03A_20120520.csv',
 '../../data/picks_2012/BABR_20120626.csv',
 '../../data/picks_2012/G09B_20121229.csv',
 '../../data/picks_2012/WISH_20120908.csv',
 '../../data/picks_2012/J17B_20120801.csv',
 '../../data/picks_2012/M06A_20120130.csv',
 '../../data/picks_2012/M06A_20120128.csv',
 '../../data/picks_2012/SNB_20120609.csv',
 '../../data/picks_2012/G03D_20120427.csv',
 '../../data/picks_2012/KHMB_20120601.csv',
 '../../data/picks_2012/J35A_20120408.csv',
 '../../data/picks_2012/G36B2_20121210.csv',
 '../../data/picks_2012/D03D_20120607.csv',
 '../../data/picks_2012/NLLB_20121121.csv',
 '../../data/picks_2012/TAKO_20120118.csv',
 '../../data/picks_2012/FN16A_20120227.csv',
 '../../data/picks_2012/KSXB_20120125.csv',
 '../../data/picks_2012/M18B_20120820.csv',
 '../../data/picks_2012/J57A_20120428.csv',
 '../../data/picks_2012/BTB_20120914.csv',
 '../../data/picks_2012/BB030_20120924.csv',
 '../../data/picks_2012/BABR_20121110.csv',
 '../../data/picks_2012/M11B_20121120.csv',
 '../../data/picks_2012/G19B_20121224.csv',
 '../../data/picks_2012/K02D_20120726.csv',
 '../../data/picks_2012/J65A_20120102.csv',
 '../../data/picks_2012/J11B_20121202.csv',
 '../../data/picks_2012/J57A_20120222.csv',
 '../../data/picks_2012/J57A_20120710.csv',
 '../../data/picks_2012/G03A_20120331.csv',
 '../../data/picks_2012/FS15B_20121130.csv',
 '../../data/picks_2012/J58A_20120531.csv',
 '../../data/picks_2012/J59A_20120531.csv',
 '../../data/picks_2012/M09B_20121213.csv',
 '../../data/picks_2012/I02D_20120918.csv',
 '../../data/picks_2012/PFB_20121219.csv',
 '../../data/picks_2012/G03D_20120404.csv',
 '../../data/picks_2012/J19B_20120908.csv',
 '../../data/picks_2012/MGB_20120809.csv',
 '../../data/picks_2012/BB070_20121214.csv',
 '../../data/picks_2012/FN16A_20120713.csv',
 '../../data/picks_2012/FN07A_20120308.csv',
 '../../data/picks_2012/BB070_20121216.csv',
 '../../data/picks_2012/M06A_20120612.csv',
 '../../data/picks_2012/J50A_20120413.csv',
 '../../data/picks_2012/FISH_20120518.csv',
 '../../data/picks_2012/LZB_20120910.csv',
 '../../data/picks_2012/I03D_20121014.csv',
 '../../data/picks_2012/J01D_20120208.csv',
 '../../data/picks_2012/J58A_20120201.csv',
 '../../data/picks_2012/M13B_20121014.csv',
 '../../data/picks_2012/G36B2_20120915.csv',
 '../../data/picks_2012/FS17B_20121124.csv',
 '../../data/picks_2012/BB030_20121121.csv',
 '../../data/picks_2012/FISH_20121201.csv',
 '../../data/picks_2012/YOUB_20120912.csv',
 '../../data/picks_2012/KBO_20120325.csv',
 '../../data/picks_2012/J25A_20120316.csv',
 '../../data/picks_2012/RADR_20120302.csv',
 '../../data/picks_2012/BB090_20121120.csv',
 '../../data/picks_2012/D03D_20120707.csv',
 '../../data/picks_2012/M13B_20120925.csv',
 '../../data/picks_2012/FN08A_20120622.csv',
 '../../data/picks_2012/I02D_20120426.csv',
 '../../data/picks_2012/KHBB_20120131.csv',
 '../../data/picks_2012/I03D_20121120.csv',
 '../../data/picks_2012/YOUB_20121127.csv',
 '../../data/picks_2012/SHB_20121229.csv',
 '../../data/picks_2012/KHMB_20121210.csv',
 '../../data/picks_2012/KHMB_20120323.csv',
 '../../data/picks_2012/J25A_20120705.csv',
 '../../data/picks_2012/KRP_20121013.csv',
 '../../data/picks_2012/BABR_20120104.csv',
 '../../data/picks_2012/SHB_20120508.csv',
 '../../data/picks_2012/G02B_20121221.csv',
 '../../data/picks_2012/G18B_20121123.csv',
 '../../data/picks_2012/NLLB_20120618.csv',
 '../../data/picks_2012/BTB_20120904.csv',
 '../../data/picks_2012/WISH_20121214.csv',
 '../../data/picks_2012/FN01A_20120628.csv',
 '../../data/picks_2012/NCBC_20120731.csv',
 '../../data/picks_2012/KMPB_20120814.csv',
 '../../data/picks_2012/L02D_20120404.csv',
 '../../data/picks_2012/BABR_20120401.csv',
 '../../data/picks_2012/FS12B_20121201.csv',
 '../../data/picks_2012/J58A_20120624.csv',
 '../../data/picks_2012/G18B_20121126.csv',
 '../../data/picks_2012/KHMB_20121220.csv',
 '../../data/picks_2012/TAKO_20120113.csv',
 '../../data/picks_2012/M06A_20120403.csv',
 '../../data/picks_2012/RADR_20120115.csv',
 '../../data/picks_2012/J65A_20120207.csv',
 '../../data/picks_2012/F04D_20120805.csv',
 '../../data/picks_2012/G03B_20120924.csv',
 '../../data/picks_2012/KMR_20120622.csv',
 '../../data/picks_2012/BABR_20120520.csv',
 '../../data/picks_2012/M14B_20121113.csv',
 '../../data/picks_2012/G25B_20121109.csv',
 '../../data/picks_2012/G28B_20121002.csv',
 '../../data/picks_2012/BABR_20121201.csv',
 '../../data/picks_2012/WISH_20120520.csv',
 '../../data/picks_2012/J49A_20120317.csv',
 '../../data/picks_2012/FS08B_20121129.csv',
 '../../data/picks_2012/PGC_20121123.csv',
 '../../data/picks_2012/FN18A_20120527.csv',
 '../../data/picks_2012/KHMB_20120925.csv',
 '../../data/picks_2012/M02A_20120525.csv',
 '../../data/picks_2012/G17B_20121228.csv',
 '../../data/picks_2012/J73A_20120630.csv',
 '../../data/picks_2012/F04D_20121218.csv',
 '../../data/picks_2012/J18B_20121118.csv',
 '../../data/picks_2012/FS01B_20121130.csv',
 '../../data/picks_2012/J59A_20120105.csv',
 '../../data/picks_2012/KMPB_20120512.csv',
 '../../data/picks_2012/I02D_20121122.csv',
 '../../data/picks_2012/G04B_20121207.csv',
 '../../data/picks_2012/DBO_20120202.csv',
 '../../data/picks_2012/FS06B_20121231.csv',
 '../../data/picks_2012/TAKO_20120816.csv',
 '../../data/picks_2012/G17B_20121215.csv',
 '../../data/picks_2012/LEBA_20120606.csv',
 '../../data/picks_2012/KEB_20120611.csv',
 '../../data/picks_2012/J33B_20120902.csv',
 '../../data/picks_2012/FS02B_20121206.csv',
 '../../data/picks_2012/M11B_20121112.csv',
 '../../data/picks_2012/SNB_20120731.csv',
 '../../data/picks_2012/KMR_20121015.csv',
 '../../data/picks_2012/J01E_20121209.csv',
 '../../data/picks_2012/JEDS_20120220.csv',
 '../../data/picks_2012/FS03B_20121028.csv',
 '../../data/picks_2012/M13B_20121107.csv',
 '../../data/picks_2012/M06A_20120320.csv',
 '../../data/picks_2012/OZB_20120220.csv',
 '../../data/picks_2012/FS07B_20121112.csv',
 '../../data/picks_2012/M14B_20121214.csv',
 '../../data/picks_2012/YOUB_20121203.csv',
 '../../data/picks_2012/FS12B_20121022.csv',
 '../../data/picks_2012/KHBB_20120330.csv',
 '../../data/picks_2012/G28B_20121103.csv',
 '../../data/picks_2012/VGZ_20121222.csv',
 '../../data/picks_2012/FISH_20120401.csv',
 '../../data/picks_2012/OFR_20120923.csv',
 '../../data/picks_2012/G03D_20121007.csv',
 '../../data/picks_2012/FS13B_20121003.csv',
 '../../data/picks_2012/L02D_20120304.csv',
 '../../data/picks_2012/J01D_20120305.csv',
 '../../data/picks_2012/NLLB_20120814.csv',
 '../../data/picks_2012/FS15B_20121011.csv',
 '../../data/picks_2012/FS15B_20121024.csv',
 '../../data/picks_2012/FS04B_20121211.csv',
 '../../data/picks_2012/G03A_20120403.csv',
 '../../data/picks_2012/KMR_20121212.csv',
 '../../data/picks_2012/J57A_20120607.csv',
 '../../data/picks_2012/M18B_20121224.csv',
 '../../data/picks_2012/J26A_20120609.csv',
 '../../data/picks_2012/KEB_20120321.csv',
 '../../data/picks_2012/J41A_20120318.csv',
 '../../data/picks_2012/G34B_20121106.csv',
 '../../data/picks_2012/J33B_20121004.csv',
 '../../data/picks_2012/LZB_20120628.csv',
 '../../data/picks_2012/PGC_20121030.csv',
 '../../data/picks_2012/KBO_20120602.csv',
 '../../data/picks_2012/G36B2_20121227.csv',
 '../../data/picks_2012/F04D_20120609.csv',
 '../../data/picks_2012/KEB_20120311.csv',
 '../../data/picks_2012/J25B_20121030.csv',
 '../../data/picks_2012/G17B_20121005.csv',
 '../../data/picks_2012/OFR_20120816.csv',
 '../../data/picks_2012/FISH_20120508.csv',
 '../../data/picks_2012/OFR_20120710.csv',
 '../../data/picks_2012/J09B_20121018.csv',
 '../../data/picks_2012/SHB_20120426.csv',
 '../../data/picks_2012/KSXB_20120208.csv',
 '../../data/picks_2012/J26A_20120216.csv',
 '../../data/picks_2012/HEBO_20120506.csv',
 '../../data/picks_2012/J27B_20120908.csv',
 '../../data/picks_2012/J57A_20120228.csv',
 '../../data/picks_2012/NC89_20121231.csv',
 '../../data/picks_2012/LEBA_20120715.csv',
 '../../data/picks_2012/I02D_20120220.csv',
 '../../data/picks_2012/G03A_20120301.csv',
 '../../data/picks_2012/J11B_20121106.csv',
 '../../data/picks_2012/FS15B_20121224.csv',
 '../../data/picks_2012/I02D_20121020.csv',
 '../../data/picks_2012/KRMB_20120430.csv',
 '../../data/picks_2012/M07A_20120420.csv',
 '../../data/picks_2012/JCC_20120307.csv',
 '../../data/picks_2012/KBO_20120329.csv',

In [7]:
len(csv_list)

105109

In [8]:
#  Concatenate all the picks in all the files produced in 1_parallel_detect_picks_elep_all_sta
all_csv =[]


for i in csv_list:
    temp = pd.read_csv(i,index_col=0)
    all_csv.append(temp)
    
df = pd.concat(all_csv, axis=0)

/tmp/ipykernel_4069706/3549658960.py:9: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat(all_csv, axis=0)
/tmp/ipykernel_4069706/3549658960.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(all_csv, axis=0)

In [9]:
# Print df
df[0:10]

,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival
0,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,NaN,2012-01-01T01:34:39.380000Z
1,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,NaN,2012-01-01T01:49:06.705000Z
2,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,NaN,2012-01-01T04:39:44.430000Z
3,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,NaN,2012-01-01T17:47:22.280000Z
4,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,NaN,2012-01-01T18:54:27.080000Z
5,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,2012-01-01T01:23:07.055000Z,NaN
6,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,2012-01-01T03:25:00.555000Z,NaN
7,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,2012-01-01T05:48:37.030000Z,NaN
8,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,2012-01-01T06:53:37.555000Z,NaN
9,,,UW,,BABR,NaN,44.62132,-123.78924,438.7,,40.0,2012-01-01T00:00:00.005000Z,,,,,,2012-01-01T09:21:36.180000Z,NaN

In [10]:
len(df)

18737281

In [11]:
df = df[df['station_code'].isin(list(stas['id']))]

In [12]:
len(df)

2327890

In [13]:
# df.to_csv('../data/datasets_all_years/all_picks_all_years_pnsn_jdf_for_picking.csv')

In [14]:
# Remove picks with the following stations due to the noise: 'FN05A', 'YOUB' and 'MGB'
df = df[~df['station_code'].isin(['FN05A', 'YOUB', 'MGB','FN14A','FN07A','J41A','J49A',
'J25B','J33B','FN18A','FN08A','M09B','G17B'])]

In [15]:
# Remove picks with the following stations due to the noise
df = df[~df['station_code'].isin(['FN05A', 'YOUB', 'MGB',
                                  'J41A','J33B','M09B','FN01A','FN08A',
                                  'FN12A','FN18A','J26A','J34A', 'J41A',
                                  'M02A','FS03B','FS05B','FS08B','G33B',
                                  'J17B','M10B','M13B','M18B'
                                 ])]

In [17]:
len(df)

2059659

In [19]:
df.to_csv('../../data/datasets_all_years/all_picks_all_years_for_assoc_pnsn_wa.csv')

### 1.3 Create a CSV file for picks for the association

In [20]:
# Assign P to P phases in the df
p_phase = df.loc[df['trace_p_arrival'].notna(), 'phase'] = "P"

In [21]:
# Filter the df 
p_stas_picks_phase = df.loc[df['trace_p_arrival'].notna(), ['station_code','trace_p_arrival','phase']]
p_stas_picks_phase

   station_code              trace_p_arrival phase
0          LEBA  2012-01-01T08:09:22.800000Z     P
1          LEBA  2012-01-01T10:47:43.425000Z     P
2          LEBA  2012-01-01T13:50:40.725000Z     P
3          LEBA  2012-01-01T15:54:26.750000Z     P
4          LEBA  2012-01-01T16:53:47.375000Z     P
..          ...                          ...   ...
9          LRIV  2011-02-22T23:52:32.335000Z     P
0          RADR  2011-11-03T16:52:31.615000Z     P
1          RADR  2011-11-03T17:45:58.290000Z     P
2          RADR  2011-11-03T23:14:21.440000Z     P
3          RADR  2011-11-03T23:50:18.890000Z     P

[1148018 rows x 3 columns]

In [22]:
# Rename the df
_p_stas_picks_phase = p_stas_picks_phase.rename(columns={"station_code": "station", "trace_p_arrival": "time"})
_p_stas_picks_phase

   station                         time phase
0     LEBA  2012-01-01T08:09:22.800000Z     P
1     LEBA  2012-01-01T10:47:43.425000Z     P
2     LEBA  2012-01-01T13:50:40.725000Z     P
3     LEBA  2012-01-01T15:54:26.750000Z     P
4     LEBA  2012-01-01T16:53:47.375000Z     P
..     ...                          ...   ...
9     LRIV  2011-02-22T23:52:32.335000Z     P
0     RADR  2011-11-03T16:52:31.615000Z     P
1     RADR  2011-11-03T17:45:58.290000Z     P
2     RADR  2011-11-03T23:14:21.440000Z     P
3     RADR  2011-11-03T23:50:18.890000Z     P

[1148018 rows x 3 columns]

In [23]:
# Assign S to S phases in the df
s_phase = df.loc[df['trace_s_arrival'].notna(), 'phase'] = "S"# Filter the df

In [24]:
# Filter the df 
s_stas_picks_phase = df.loc[df['trace_s_arrival'].notna(), ['station_code','trace_s_arrival','phase']]
s_stas_picks_phase

   station_code              trace_s_arrival phase
18         LEBA  2012-01-01T01:27:34.625000Z     S
19         LEBA  2012-01-01T10:47:44.425000Z     S
20         LEBA  2012-01-01T14:02:02.325000Z     S
21         LEBA  2012-01-01T15:35:49.675000Z     S
22         LEBA  2012-01-01T18:49:36.700000Z     S
..          ...                          ...   ...
7          RADR  2011-11-03T19:00:33.865000Z     S
8          RADR  2011-11-03T20:13:59.665000Z     S
9          RADR  2011-11-03T20:27:31.990000Z     S
10         RADR  2011-11-03T20:35:44.990000Z     S
11         RADR  2011-11-03T21:38:03.715000Z     S

[911641 rows x 3 columns]

In [25]:
# Rename the df
_s_stas_picks_phase = s_stas_picks_phase.rename(columns={"station_code": "station", "trace_s_arrival": "time"})
_s_stas_picks_phase

   station                         time phase
18    LEBA  2012-01-01T01:27:34.625000Z     S
19    LEBA  2012-01-01T10:47:44.425000Z     S
20    LEBA  2012-01-01T14:02:02.325000Z     S
21    LEBA  2012-01-01T15:35:49.675000Z     S
22    LEBA  2012-01-01T18:49:36.700000Z     S
..     ...                          ...   ...
7     RADR  2011-11-03T19:00:33.865000Z     S
8     RADR  2011-11-03T20:13:59.665000Z     S
9     RADR  2011-11-03T20:27:31.990000Z     S
10    RADR  2011-11-03T20:35:44.990000Z     S
11    RADR  2011-11-03T21:38:03.715000Z     S

[911641 rows x 3 columns]

In [26]:
# Concatenate the P and S picks
picks = pd.concat(objs = [_p_stas_picks_phase,_s_stas_picks_phase] , axis=0)
picks

   station                         time phase
0     LEBA  2012-01-01T08:09:22.800000Z     P
1     LEBA  2012-01-01T10:47:43.425000Z     P
2     LEBA  2012-01-01T13:50:40.725000Z     P
3     LEBA  2012-01-01T15:54:26.750000Z     P
4     LEBA  2012-01-01T16:53:47.375000Z     P
..     ...                          ...   ...
7     RADR  2011-11-03T19:00:33.865000Z     S
8     RADR  2011-11-03T20:13:59.665000Z     S
9     RADR  2011-11-03T20:27:31.990000Z     S
10    RADR  2011-11-03T20:35:44.990000Z     S
11    RADR  2011-11-03T21:38:03.715000Z     S

[2059659 rows x 3 columns]

In [27]:
# Swap the time and phase columns
picks = picks.iloc[:,[0,2,1]]
picks = picks.reset_index(drop=True)
picks

        station phase                         time
0          LEBA     P  2012-01-01T08:09:22.800000Z
1          LEBA     P  2012-01-01T10:47:43.425000Z
2          LEBA     P  2012-01-01T13:50:40.725000Z
3          LEBA     P  2012-01-01T15:54:26.750000Z
4          LEBA     P  2012-01-01T16:53:47.375000Z
...         ...   ...                          ...
2059654    RADR     S  2011-11-03T19:00:33.865000Z
2059655    RADR     S  2011-11-03T20:13:59.665000Z
2059656    RADR     S  2011-11-03T20:27:31.990000Z
2059657    RADR     S  2011-11-03T20:35:44.990000Z
2059658    RADR     S  2011-11-03T21:38:03.715000Z

[2059659 rows x 3 columns]

In [28]:
picks[0:20]

   station phase                         time
0     LEBA     P  2012-01-01T08:09:22.800000Z
1     LEBA     P  2012-01-01T10:47:43.425000Z
2     LEBA     P  2012-01-01T13:50:40.725000Z
3     LEBA     P  2012-01-01T15:54:26.750000Z
4     LEBA     P  2012-01-01T16:53:47.375000Z
5     LEBA     P  2012-01-01T16:56:35.625000Z
6     LEBA     P  2012-01-01T17:13:39.375000Z
7     LEBA     P  2012-01-01T17:18:54.050000Z
8     LEBA     P  2012-01-01T17:59:55.450000Z
9     LEBA     P  2012-01-01T18:01:46.925000Z
10    LEBA     P  2012-01-01T20:33:30.550000Z
11    LEBA     P  2012-01-01T20:38:28.925000Z
12    LEBA     P  2012-01-01T20:56:08.600000Z
13    LEBA     P  2012-01-01T21:19:46.400000Z
14    LEBA     P  2012-01-01T21:23:31.300000Z
15    LEBA     P  2012-01-01T21:24:23.800000Z
16    LEBA     P  2012-01-01T22:36:38.500000Z
17    LEBA     P  2012-01-01T23:32:54.850000Z
18    NLLB     P  2012-01-01T01:23:18.650000Z
19    NLLB     P  2012-01-01T05:38:39.100000Z

In [29]:
# Save the these picks to the data folder
picks.to_csv("../../data/datasets_all_years/picks_pnsn_wa.csv")

## 2. Create the stations data frame

In [30]:
# Print the stations for which the picks were detected in 1_parallel_detect_picks_elep_all_sta 
stations = df.drop_duplicates(subset='station_code')
stations

,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival,phase
0,,,UW,,LEBA,NaN,46.545898,-123.563202,78.6,,40.0,2012-01-01T00:00:00.025000Z,,,,,,NaN,2012-01-01T08:09:22.800000Z,P
0,,,CN,,NLLB,NaN,49.227100,-123.988200,199.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T01:23:18.650000Z,P
0,,,TA,,G03D,NaN,45.211498,-123.264099,222.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T01:07:03.175000Z,P
0,,,CN,,SHB,NaN,49.598500,-123.877100,1129.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T03:03:06.025000Z,P
0,,,UW,,LRIV,NaN,48.057500,-123.504000,293.8,,40.0,2012-01-01T00:00:00.015000Z,,,,,,NaN,2012-01-01T03:13:16.865000Z,P
0,,,CN,,PGC,NaN,48.649800,-123.452100,12.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T01:36:16.525000Z,P
0,,,UW,,RADR,NaN,46.421810,-123.798970,591.4,,40.0,2012-01-01T00:00:00.015000Z,,,,,,2012-01-01T05:38:51.215000Z,NaN,S
0,,,CN,,LZB,NaN,48.612200,-123.824000,794.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T03:19:08.475000Z,P
0,,,UW,,MEGW,NaN,46.266090,-123.877090,351.0,,50.0,2012-01-01T00:00:00.003000Z,,,,,,NaN,2012-01-01T14:55:49.143000Z,P
0,,,UW,,OFR,NaN,47.933128,-124.396042,152.0,,50.0,2012-01-01T00:00:00.009000Z,,,,,,NaN,2012-01-01T00:03:38.889000Z,P
0,,,UW,,HEBO,NaN,45.213501,-123.755386,875.0,,40.0,2012-01-01T00:00:00.015000Z,,,,,,NaN,2012-01-01T22:34:50.665000Z,P
0,,,CN,,VGZ,NaN,48.413100,-123.325100,67.0,,100.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T03:09:25.120000Z,P
0,,,CN,,OZB,NaN,48.961200,-125.497800,626.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T04:41:26.050000Z,P
0,,,UW,,FISH,NaN,45.930600,-123.559100,327.0,,40.0,2012-01-01T17:47:53.525000Z,,,,,,NaN,2012-01-01T17:55:19.050000Z,P
0,,,TA,,F04D,NaN,46.082901,-123.010803,236.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T02:05:07.300000Z,P
0,,,TA,,D03D,NaN,47.534698,-123.089401,262.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T05:38:47.800000Z,P
0,,,CN,,PFB,NaN,48.574700,-124.454100,449.0,,100.0,2012-11-01T00:00:00.000000Z,,,,,,NaN,2012-11-01T05:36:19.970000Z,P
0,,,UW,,WISH,NaN,47.116980,-123.771180,45.0,,40.0,2012-05-10T00:00:00.015000Z,,,,,,NaN,2012-05-10T00:09:35.340000Z,P
0,,,CN,,BTB,NaN,49.468600,-125.522600,1607.0,,100.0,2012-09-22T00:00:00.000000Z,,,,,,NaN,2012-09-22T00:40:32.870000Z,P
0,,,CN,,SNB,NaN,48.775100,-123.172300,402.0,,100.0,2012-06-09T00:00:00.000000Z,,,,,,NaN,2012-06-09T00:35:08.540000Z,P
0,,,CN,,BFSB,NaN,48.833600,-125.136000,33.0,,100.0,2014-01-08T00:00:00.000000Z,,,,,,NaN,2014-01-08T01:08:16.550000Z,P
0,,,CN,,CLRS,NaN,48.820300,-124.130900,174.0,,100.0,2014-11-29T00:00:00.000000Z,,,,,,NaN,2014-11-29T00:02:05.790000Z,P
0,,,C8,,TOFB,NaN,49.154300,-125.907800,13.0,,100.0,2015-06-25T00:00:00.000000Z,,,,,,NaN,2015-06-25T00:06:25.980000Z,P
0,,,C8,,PA12,NaN,48.648200,-123.449600,10.0,,100.0,2015-03-25T00:00:00.000000Z,,,,,,NaN,2015-03-25T00:00:17.320000Z,P
0,,,C8,,PA01,NaN,48.652600,-123.447000,3.0,,100.0,2015-10-21T00:00:00.000000Z,,,,,,NaN,2015-10-21T00:04:53.240000Z,P
0,,,C8,,PA05,NaN,48.649700,-123.443800,8.0,,100.0,2015-05-24T00:00:00.000000Z,,,,,,NaN,2015-05-24T00:13:20.960000Z,P
0,,,C8,,PA02,NaN,48.651800,-123.448900,3.0,,100.0,2015-12-30T16:58:21.350000Z,,,,,,NaN,2015-12-30T17:10:31.340000Z,P
0,,,C8,,MWAB,NaN,49.741100,-125.303200,1176.0,,100.0,2015-07-17T00:00:00.000000Z,,,,,,NaN,2015-07-17T00:06:52.500000Z,P
0,,,C8,,SPLB,NaN,49.892100,-125.652600,276.0,,100.0,2015-07-29T00:00:00.000000Z,,,,,,NaN,2015-07-29T00:03:02.050000Z,P
0,,,C8,,SOKB,NaN,48.394700,-123.673100,45.0,,100.0,2015-01-17T00:00:00.000000Z,,,,,,NaN,2015-01-17T00:00:40.800000Z,P
0,,,UW,,SQM,NaN,48.073681,-123.048058,45.0,,50.0,2011-07-01T00:00:00.006000Z,,,,,,NaN,2011-07-01T01:53:57.466000Z,P
0,,,CN,,BMSB,NaN,48.835600,-125.135500,10.0,,40.0,2011-07-17T00:00:00.000000Z,,,,,,NaN,2011-07-17T00:05:14.850000Z,P

In [31]:
# Obtain only the columns you need for assoication
_stations = stations.iloc[:,[4,7,6,8]]
_stations

,station_code,station_longitude_deg,station_latitude_deg,station_elevation_m
0,LEBA,-123.563202,46.545898,78.6
0,NLLB,-123.988200,49.227100,199.0
0,G03D,-123.264099,45.211498,222.0
0,SHB,-123.877100,49.598500,1129.0
0,LRIV,-123.504000,48.057500,293.8
0,PGC,-123.452100,48.649800,12.0
0,RADR,-123.798970,46.421810,591.4
0,LZB,-123.824000,48.612200,794.0
0,MEGW,-123.877090,46.266090,351.0
0,OFR,-124.396042,47.933128,152.0
0,HEBO,-123.755386,45.213501,875.0
0,VGZ,-123.325100,48.413100,67.0
0,OZB,-125.497800,48.961200,626.0
0,FISH,-123.559100,45.930600,327.0
0,F04D,-123.010803,46.082901,236.0
0,D03D,-123.089401,47.534698,262.0
0,PFB,-124.454100,48.574700,449.0
0,WISH,-123.771180,47.116980,45.0
0,BTB,-125.522600,49.468600,1607.0
0,SNB,-123.172300,48.775100,402.0
0,BFSB,-125.136000,48.833600,33.0
0,CLRS,-124.130900,48.820300,174.0
0,TOFB,-125.907800,49.154300,13.0
0,PA12,-123.449600,48.648200,10.0
0,PA01,-123.447000,48.652600,3.0
0,PA05,-123.443800,48.649700,8.0
0,PA02,-123.448900,48.651800,3.0
0,MWAB,-125.303200,49.741100,1176.0
0,SPLB,-125.652600,49.892100,276.0
0,SOKB,-123.673100,48.394700,45.0
0,SQM,-123.048058,48.073681,45.0
0,BMSB,-125.135500,48.835600,10.0

In [32]:
# Rename the columns
_stations = _stations.rename(columns={'station_code': 'id', 'station_longitude_deg': 'longitude', 'station_latitude_deg': 'latitude', 'station_elevation_m': 'elevation'})
_stations = _stations.reset_index(drop=True)
_stations

      id   longitude   latitude  elevation
0   LEBA -123.563202  46.545898       78.6
1   NLLB -123.988200  49.227100      199.0
2   G03D -123.264099  45.211498      222.0
3    SHB -123.877100  49.598500     1129.0
4   LRIV -123.504000  48.057500      293.8
5    PGC -123.452100  48.649800       12.0
6   RADR -123.798970  46.421810      591.4
7    LZB -123.824000  48.612200      794.0
8   MEGW -123.877090  46.266090      351.0
9    OFR -124.396042  47.933128      152.0
10  HEBO -123.755386  45.213501      875.0
11   VGZ -123.325100  48.413100       67.0
12   OZB -125.497800  48.961200      626.0
13  FISH -123.559100  45.930600      327.0
14  F04D -123.010803  46.082901      236.0
15  D03D -123.089401  47.534698      262.0
16   PFB -124.454100  48.574700      449.0
17  WISH -123.771180  47.116980       45.0
18   BTB -125.522600  49.468600     1607.0
19   SNB -123.172300  48.775100      402.0
20  BFSB -125.136000  48.833600       33.0
21  CLRS -124.130900  48.820300      174.0
22  TOFB -125.907800  49.154300       13.0
23  PA12 -123.449600  48.648200       10.0
24  PA01 -123.447000  48.652600        3.0
25  PA05 -123.443800  48.649700        8.0
26  PA02 -123.448900  48.651800        3.0
27  MWAB -125.303200  49.741100     1176.0
28  SPLB -125.652600  49.892100      276.0
29  SOKB -123.673100  48.394700       45.0
30   SQM -123.048058  48.073681       45.0
31  BMSB -125.135500  48.835600       10.0

In [33]:
# Create  a csv file
_stations.to_csv('../../data/datasets_all_years/all_stations_pnsn_wa.csv')

## 3. Make pick and station data frames for different CI years

### 3.1 Make pick and station data frames for CI year 1 of 2012

### 3.1.1 Picks

In [34]:
t = pd.Timestamp(f'{year}-7-31 00:00:00.000000+0000', tz='UTC')
picks = pd.read_csv("../data/datasets_2012/picks_2012.csv",index_col=0)
picks["time"] = pd.to_datetime(picks['time'], utc = True)
picks_CI1 = picks[picks['time']<=t]
picks_CI1

FileNotFoundError: [Errno 2] No such file or directory: '../data/datasets_2012/picks_2012.csv'

In [39]:
picks_CI1.to_csv('../data/datasets_2012/picks_2012_CI1.csv')

### 3.1.2 Stations

In [43]:
stas = pd.read_csv("../data/datasets_2012/all_stations_2012.csv",index_col=0)
stas

        id   longitude   latitude  elevation
0      PGC -123.452100  48.649800       12.0
1     KSXB -123.876884  41.830379     1136.0
2      JCC -124.029549  40.817451       27.2
3      VGZ -123.325100  48.413100       67.0
4     J01D -123.931396  43.161400      131.0
..     ...         ...        ...        ...
110  BB060 -126.113297  42.856098    -2795.0
111  FS14B -124.591797  40.495499     -107.0
112   M06A -124.926804  45.529499    -1439.0
113  FS11B -124.577797  40.429199     -132.0
114   G20B -126.613297  41.298698    -3141.0

[115 rows x 4 columns]

In [50]:
stas_CI1 = list(picks_CI1['station'].drop_duplicates().values)
stas_CI1

['PGC',
 'KSXB',
 'JCC',
 'VGZ',
 'J01D',
 'LEBA',
 'KHBB',
 'J50A',
 'FN14A',
 'KCT',
 'KBO',
 'OZB',
 'J51A',
 'SHB',
 'J25A',
 'KEB',
 'LZB',
 'FN16A',
 'M03A',
 'FN07A',
 'D03D',
 'DBO',
 'KRP',
 'J59A',
 'I02D',
 'TAKO',
 'J42A',
 'MEGW',
 'KRMB',
 'KMPB',
 'F04D',
 'HEBO',
 'J57A',
 'J43A',
 'J49A',
 'G03D',
 'J73A',
 'FORK',
 'WISH',
 'RADR',
 'M08A',
 'L02D',
 'BABR',
 'NLLB',
 'SNB',
 'KHMB',
 'J35A',
 'K02D',
 'J65A',
 'G03A',
 'J58A',
 'KMR',
 'JEDS',
 'FISH',
 'OFR',
 'M07A',
 'PFB',
 'M01A',
 'I03D',
 'LRIV',
 'J33A',
 'BTB',
 'NC89',
 'M06A',
 'J25B',
 'NCBC']

In [52]:
_stas_CI1 = stas.loc[stas['id'].isin(stas_CI1)]
_stas_CI1

       id   longitude   latitude  elevation
0     PGC -123.452100  48.649800       12.0
1    KSXB -123.876884  41.830379     1136.0
2     JCC -124.029549  40.817451       27.2
3     VGZ -123.325100  48.413100       67.0
4    J01D -123.931396  43.161400      131.0
..    ...         ...        ...        ...
101  NC89 -126.848767  48.670537    -1258.0
102  M07A -125.116798  44.898701    -1356.5
104  M01A -126.722099  49.150398     -132.9
108  J33A -124.570801  45.106602     -348.7
112  M06A -124.926804  45.529499    -1439.0

[66 rows x 4 columns]

In [53]:
_stas_CI1.to_csv('../data/datasets_2012/stations_2012_CI1.csv')