## Notebook for formatting data frames for phase association

In [2]:
import pandas as pd
import numpy as np
import glob

In [22]:
pd.read_csv('../data/picks/SHB_20120101.csv')

,Unnamed: 0,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival
0,0,,,CN,,SHB,NaN,49.5985,-123.8771,1129.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,NaN,2012-01-01T03:03:06.025000Z
1,1,,,CN,,SHB,NaN,49.5985,-123.8771,1129.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,2012-01-01T08:07:08.950000Z,NaN
2,2,,,CN,,SHB,NaN,49.5985,-123.8771,1129.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,2012-01-01T08:42:46.675000Z,NaN
3,3,,,CN,,SHB,NaN,49.5985,-123.8771,1129.0,,40.0,2012-01-01T00:00:00.000000Z,,,,,,2012-01-01T17:27:42.375000Z,NaN

## 1. Format data frames for picks

### 1.1 Format one data frame first (no need to run this section)

In [ ]:
df_FS09B_20121001 = pd.read_csv('../data/catalogs_elep_all_stations_20121001_to_20121031/FS09B_20121001.csv')

In [ ]:
df_FS09B_20121001

In [ ]:
df_FS09B_20121001['phase'] = np.nan
df_FS09B_20121001

In [ ]:
p_picks = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'trace_p_arrival']
p_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'phase'] = "P"
p_stations = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'station_code']
p_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'phase']

In [ ]:
p_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_p_arrival'].notna(), 'phase']

In [ ]:
# print(p_picks)
# print(p_phase)
# print(p_stations)
p_phase

In [ ]:
s_picks =  df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'trace_s_arrival']
s_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'phase'] = "S"
s_stations = df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'station_code']
s_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'phase']

In [ ]:
s_phase = df_FS09B_20121001.loc[df_FS09B_20121001['trace_s_arrival'].notna(), 'phase']

In [ ]:
s_phase

In [ ]:
time = pd.concat(objs = [p_picks,s_picks] , axis=0)
phase = pd.concat(objs = [p_phase,s_phase] , axis=0)

In [ ]:
print(time)
print(phase)

In [ ]:
stations = df_FS09B_20121001['station_code']
stations

In [ ]:
picks = pd.concat(objs = [stations,phase,time] , axis=1)

In [ ]:
picks

### 1.2 Concatenate data frames from several stations and format

In [3]:
# Gather all the files that we produced in 1_parallel_detect_picks_elep_all_sta
csv_list = glob.glob('../data/picks_2011/*.csv')

In [4]:
# Print csv_list
csv_list

['../data/picks_2011/FORK_20110607.csv',
 '../data/picks_2011/LZB_20110604.csv',
 '../data/picks_2011/G03D_20110627.csv',
 '../data/picks_2011/J33A_20111121.csv',
 '../data/picks_2011/W04_20110217.csv',
 '../data/picks_2011/LRIV_20111125.csv',
 '../data/picks_2011/W08_20110209.csv',
 '../data/picks_2011/LEBA_20110702.csv',
 '../data/picks_2011/WISH_20110123.csv',
 '../data/picks_2011/PGC_20111025.csv',
 '../data/picks_2011/J01D_20110724.csv',
 '../data/picks_2011/K02D_20110914.csv',
 '../data/picks_2011/SHB_20110308.csv',
 '../data/picks_2011/SQM_20110701.csv',
 '../data/picks_2011/YOUB_20110322.csv',
 '../data/picks_2011/J01D_20110511.csv',
 '../data/picks_2011/I02D_20110118.csv',
 '../data/picks_2011/K02D_20111221.csv',
 '../data/picks_2011/KHMB_20110329.csv',
 '../data/picks_2011/W08_20110302.csv',
 '../data/picks_2011/J73A_20111114.csv',
 '../data/picks_2011/SNB_20110602.csv',
 '../data/picks_2011/J33A_20111206.csv',
 '../data/picks_2011/KBO_20110324.csv',
 '../data/picks_2011/KHBB_20110526.csv',
 '../data/picks_2011/LEBA_20110120.csv',
 '../data/picks_2011/LRIV_20110419.csv',
 '../data/picks_2011/J65A_20111108.csv',
 '../data/picks_2011/OFR_20110120.csv',
 '../data/picks_2011/FORK_20110124.csv',
 '../data/picks_2011/KHBB_20110720.csv',
 '../data/picks_2011/K02D_20111108.csv',
 '../data/picks_2011/SNB_20110810.csv',
 '../data/picks_2011/KBO_20110204.csv',
 '../data/picks_2011/NLLB_20111206.csv',
 '../data/picks_2011/OZB_20111101.csv',
 '../data/picks_2011/TAKO_20110603.csv',
 '../data/picks_2011/J41A_20111204.csv',
 '../data/picks_2011/SHB_20110913.csv',
 '../data/picks_2011/JCC_20110312.csv',
 '../data/picks_2011/I02D_20111019.csv',
 '../data/picks_2011/LZB_20111019.csv',
 '../data/picks_2011/NLLB_20110725.csv',
 '../data/picks_2011/J41A_20110824.csv',
 '../data/picks_2011/JEDS_20111119.csv',
 '../data/picks_2011/FORK_20110510.csv',
 '../data/picks_2011/J34A_20111221.csv',
 '../data/picks_2011/YOUB_20110130.csv',
 '../data/picks_2011/SNB_20111005.csv',
 '../data/picks_2011/LZB_20110711.csv',
 '../data/picks_2011/L02D_20111005.csv',
 '../data/picks_2011/OZB_20110804.csv',
 '../data/picks_2011/PGC_20110619.csv',
 '../data/picks_2011/KSXB_20110819.csv',
 '../data/picks_2011/I02D_20110107.csv',
 '../data/picks_2011/MGB_20111002.csv',
 '../data/picks_2011/OFR_20111113.csv',
 '../data/picks_2011/DBO_20111130.csv',
 '../data/picks_2011/SHB_20110425.csv',
 '../data/picks_2011/W06_20110121.csv',
 '../data/picks_2011/PFB_20110307.csv',
 '../data/picks_2011/FN08A_20111214.csv',
 '../data/picks_2011/K02D_20111030.csv',
 '../data/picks_2011/KCT_20111001.csv',
 '../data/picks_2011/VGZ_20110807.csv',
 '../data/picks_2011/FN08A_20110913.csv',
 '../data/picks_2011/JCC_20110126.csv',
 '../data/picks_2011/FN08A_20110813.csv',
 '../data/picks_2011/J65A_20111101.csv',
 '../data/picks_2011/M06A_20111211.csv',
 '../data/picks_2011/I03D_20110226.csv',
 '../data/picks_2011/KEB_20110908.csv',
 '../data/picks_2011/KMR_20111008.csv',
 '../data/picks_2011/OFR_20111024.csv',
 '../data/picks_2011/J42A_20111018.csv',
 '../data/picks_2011/KMPB_20110809.csv',
 '../data/picks_2011/W09_20110314.csv',
 '../data/picks_2011/SHB_20110910.csv',
 '../data/picks_2011/KMR_20110724.csv',
 '../data/picks_2011/BMSB_20110717.csv',
 '../data/picks_2011/KMPB_20110512.csv',
 '../data/picks_2011/KHBB_20111027.csv',
 '../data/picks_2011/PGC_20110420.csv',
 '../data/picks_2011/KMPB_20110114.csv',
 '../data/picks_2011/OFR_20110624.csv',
 '../data/picks_2011/M03A_20111204.csv',
 '../data/picks_2011/WISH_20111216.csv',
 '../data/picks_2011/W04_20110114.csv',
 '../data/picks_2011/BMSB_20111011.csv',
 '../data/picks_2011/KEB_20110617.csv',
 '../data/picks_2011/I03D_20111217.csv',
 '../data/picks_2011/J59A_20111207.csv',
 '../data/picks_2011/SHB_20110206.csv',
 '../data/picks_2011/D03D_20110907.csv',
 '../data/picks_2011/JCC_20110429.csv',
 '../data/picks_2011/FN08A_20111224.csv',
 '../data/picks_2011/I03D_20110825.csv',
 '../data/picks_2011/FN05A_20110909.csv',
 '../data/picks_2011/NC89_20110408.csv',
 '../data/picks_2011/J42A_20111022.csv',
 '../data/picks_2011/KHBB_20111031.csv',
 '../data/picks_2011/FISH_20110825.csv',
 '../data/picks_2011/KHBB_20110824.csv',
 '../data/picks_2011/JCC_20110602.csv',
 '../data/picks_2011/FISH_20110616.csv',
 '../data/picks_2011/KEB_20111015.csv',
 '../data/picks_2011/KMR_20110731.csv',
 '../data/picks_2011/KSXB_20110818.csv',
 '../data/picks_2011/FISH_20110105.csv',
 '../data/picks_2011/FN12A_20110919.csv',
 '../data/picks_2011/LZB_20110313.csv',
 '../data/picks_2011/D03D_20111209.csv',
 '../data/picks_2011/HEBO_20110217.csv',
 '../data/picks_2011/FISH_20110220.csv',
 '../data/picks_2011/LEBA_20110214.csv',
 '../data/picks_2011/SHB_20110131.csv',
 '../data/picks_2011/DBO_20111108.csv',
 '../data/picks_2011/W01_20110210.csv',
 '../data/picks_2011/KRMB_20110928.csv',
 '../data/picks_2011/JEDS_20111206.csv',
 '../data/picks_2011/J01D_20111001.csv',
 '../data/picks_2011/KHMB_20110303.csv',
 '../data/picks_2011/SHB_20110315.csv',
 '../data/picks_2011/JEDS_20111124.csv',
 '../data/picks_2011/J49A_20111030.csv',
 '../data/picks_2011/I03D_20110117.csv',
 '../data/picks_2011/J01D_20110709.csv',
 '../data/picks_2011/J41A_20110814.csv',
 '../data/picks_2011/PGC_20110410.csv',
 '../data/picks_2011/W06_20110130.csv',
 '../data/picks_2011/K02D_20110519.csv',
 '../data/picks_2011/BTB_20110617.csv',
 '../data/picks_2011/I03D_20110209.csv',
 '../data/picks_2011/I02D_20110301.csv',
 '../data/picks_2011/BMSB_20110501.csv',
 '../data/picks_2011/FN05A_20111019.csv',
 '../data/picks_2011/BTB_20111118.csv',
 '../data/picks_2011/SHB_20111105.csv',
 '../data/picks_2011/MGB_20111119.csv',
 '../data/picks_2011/W08_20110206.csv',
 '../data/picks_2011/SNB_20111105.csv',
 '../data/picks_2011/RADR_20110904.csv',
 '../data/picks_2011/PFB_20110813.csv',
 '../data/picks_2011/LEBA_20111028.csv',
 '../data/picks_2011/KHBB_20110418.csv',
 '../data/picks_2011/LRIV_20110120.csv',
 '../data/picks_2011/M06A_20111020.csv',
 '../data/picks_2011/J01D_20110824.csv',
 '../data/picks_2011/HEBO_20110704.csv',
 '../data/picks_2011/M08A_20111114.csv',
 '../data/picks_2011/LEBA_20110810.csv',
 '../data/picks_2011/KMR_20110722.csv',
 '../data/picks_2011/SNB_20110910.csv',
 '../data/picks_2011/DBO_20110324.csv',
 '../data/picks_2011/WISH_20110314.csv',
 '../data/picks_2011/FN08A_20111017.csv',
 '../data/picks_2011/M06A_20111104.csv',
 '../data/picks_2011/W02_20110625.csv',
 '../data/picks_2011/KHBB_20111202.csv',
 '../data/picks_2011/MEGW_20110414.csv',
 '../data/picks_2011/J51A_20111201.csv',
 '../data/picks_2011/G03A_20111216.csv',
 '../data/picks_2011/BTB_20110227.csv',
 '../data/picks_2011/I03D_20111126.csv',
 '../data/picks_2011/M02A_20111109.csv',
 '../data/picks_2011/TAKO_20110323.csv',
 '../data/picks_2011/LRIV_20110907.csv',
 '../data/picks_2011/I02D_20110414.csv',
 '../data/picks_2011/BTB_20110326.csv',
 '../data/picks_2011/FN14A_20110919.csv',
 '../data/picks_2011/J65A_20111027.csv',
 '../data/picks_2011/BTB_20111227.csv',
 '../data/picks_2011/TAKO_20110126.csv',
 '../data/picks_2011/MEGW_20111216.csv',
 '../data/picks_2011/BMSB_20110701.csv',
 '../data/picks_2011/M07A_20111031.csv',
 '../data/picks_2011/DBO_20110210.csv',
 '../data/picks_2011/KMR_20110420.csv',
 '../data/picks_2011/YOUB_20110901.csv',
 '../data/picks_2011/M06A_20111219.csv',
 '../data/picks_2011/BMSB_20111004.csv',
 '../data/picks_2011/SQM_20110415.csv',
 '../data/picks_2011/KMR_20110624.csv',
 '../data/picks_2011/JEDS_20111215.csv',
 '../data/picks_2011/G03D_20110426.csv',
 '../data/picks_2011/LRIV_20110101.csv',
 '../data/picks_2011/D03D_20110506.csv',
 '../data/picks_2011/KEB_20110122.csv',
 '../data/picks_2011/W10_20110123.csv',
 '../data/picks_2011/D03D_20110217.csv',
 '../data/picks_2011/K02D_20110121.csv',
 '../data/picks_2011/DBO_20110228.csv',
 '../data/picks_2011/KHMB_20110711.csv',
 '../data/picks_2011/WISH_20111008.csv',
 '../data/picks_2011/KCT_20111117.csv',
 '../data/picks_2011/WISH_20110930.csv',
 '../data/picks_2011/FORK_20111123.csv',
 '../data/picks_2011/KBO_20111205.csv',
 '../data/picks_2011/I03D_20110219.csv',
 '../data/picks_2011/FN08A_20110928.csv',
 '../data/picks_2011/FN05A_20111109.csv',
 '../data/picks_2011/PFB_20110606.csv',
 '../data/picks_2011/M08A_20111225.csv',
 '../data/picks_2011/FISH_20110815.csv',
 '../data/picks_2011/LZB_20110329.csv',
 '../data/picks_2011/KMPB_20110508.csv',
 '../data/picks_2011/J51A_20111111.csv',
 '../data/picks_2011/KRP_20110622.csv',
 '../data/picks_2011/J73A_20111018.csv',
 '../data/picks_2011/KRMB_20110807.csv',
 '../data/picks_2011/LZB_20110413.csv',
 '../data/picks_2011/I03D_20110103.csv',
 '../data/picks_2011/MGB_20110127.csv',
 '../data/picks_2011/LZB_20110420.csv',
 '../data/picks_2011/NLLB_20111115.csv',
 '../data/picks_2011/BABR_20111005.csv',
 '../data/picks_2011/MEGW_20111001.csv',
 '../data/picks_2011/L02D_20110117.csv',
 '../data/picks_2011/NLLB_20110623.csv',
 '../data/picks_2011/LRIV_20110626.csv',
 '../data/picks_2011/J01D_20111102.csv',
 '../data/picks_2011/FISH_20110112.csv',
 '../data/picks_2011/JEDS_20111014.csv',
 '../data/picks_2011/JCC_20110311.csv',
 '../data/picks_2011/FN01A_20110904.csv',
 '../data/picks_2011/KSXB_20110520.csv',
 '../data/picks_2011/J49A_20111226.csv',
 '../data/picks_2011/YOUB_20110128.csv',
 '../data/picks_2011/FN07A_20110814.csv',
 '../data/picks_2011/KMR_20110217.csv',
 '../data/picks_2011/FN07A_20111222.csv',
 '../data/picks_2011/FORK_20110501.csv',
 '../data/picks_2011/FN16A_20111028.csv',
 '../data/picks_2011/JCC_20110428.csv',
 '../data/picks_2011/G03D_20110407.csv',
 '../data/picks_2011/NLLB_20110205.csv',
 '../data/picks_2011/I03D_20111101.csv',
 '../data/picks_2011/PGC_20111010.csv',
 '../data/picks_2011/NLLB_20110907.csv',
 '../data/picks_2011/L02D_20110223.csv',
 '../data/picks_2011/J41A_20110808.csv',
 '../data/picks_2011/KMR_20110501.csv',
 '../data/picks_2011/I03D_20110129.csv',
 '../data/picks_2011/DBO_20110527.csv',
 '../data/picks_2011/KHMB_20111118.csv',
 '../data/picks_2011/MGB_20110523.csv',
 '../data/picks_2011/JCC_20110224.csv',
 '../data/picks_2011/PGC_20110113.csv',
 '../data/picks_2011/KMR_20110526.csv',
 '../data/picks_2011/F04D_20110603.csv',
 '../data/picks_2011/J65A_20111217.csv',
 '../data/picks_2011/JCC_20111229.csv',
 '../data/picks_2011/YOUB_20110328.csv',
 '../data/picks_2011/KHBB_20110917.csv',
 '../data/picks_2011/W01_20110227.csv',
 '../data/picks_2011/WISH_20110710.csv',
 '../data/picks_2011/I03D_20110630.csv',
 '../data/picks_2011/KMR_20111005.csv',
 '../data/picks_2011/OZB_20110901.csv',
 '../data/picks_2011/KHMB_20110530.csv',
 '../data/picks_2011/MEGW_20110422.csv',
 '../data/picks_2011/KMR_20110812.csv',
 '../data/picks_2011/KMR_20110827.csv',
 '../data/picks_2011/FN07A_20111223.csv',
 '../data/picks_2011/LRIV_20110429.csv',
 '../data/picks_2011/D03D_20110908.csv',
 '../data/picks_2011/VGZ_20111026.csv',
 '../data/picks_2011/SNB_20110508.csv',
 '../data/picks_2011/MGB_20110419.csv',
 '../data/picks_2011/FN12A_20110828.csv',
 '../data/picks_2011/SNB_20110906.csv',
 '../data/picks_2011/W09_20110626.csv',
 '../data/picks_2011/JCC_20111204.csv',
 '../data/picks_2011/I02D_20110508.csv',
 '../data/picks_2011/KHBB_20110501.csv',
 '../data/picks_2011/PFB_20110203.csv',
 '../data/picks_2011/J26A_20111025.csv',
 '../data/picks_2011/KRP_20110430.csv',
 '../data/picks_2011/L02D_20110724.csv',
 '../data/picks_2011/MGB_20111219.csv',
 '../data/picks_2011/MGB_20110125.csv',
 '../data/picks_2011/KHMB_20110822.csv',
 '../data/picks_2011/NLLB_20110118.csv',
 '../data/picks_2011/NC89_20110323.csv',
 '../data/picks_2011/FN18A_20111025.csv',
 '../data/picks_2011/FN01A_20111224.csv',
 '../data/picks_2011/J58A_20111024.csv',
 '../data/picks_2011/WISH_20110204.csv',
 '../data/picks_2011/K02D_20110515.csv',
 '../data/picks_2011/JEDS_20110810.csv',
 '../data/picks_2011/LEBA_20111208.csv',
 '../data/picks_2011/K02D_20111011.csv',
 '../data/picks_2011/WISH_20110108.csv',
 '../data/picks_2011/I03D_20110506.csv',
 '../data/picks_2011/J59A_20111229.csv',
 '../data/picks_2011/I03D_20110803.csv',
 '../data/picks_2011/SNB_20110520.csv',
 '../data/picks_2011/HEBO_20110526.csv',
 '../data/picks_2011/PFB_20110626.csv',
 '../data/picks_2011/KRP_20111016.csv',
 '../data/picks_2011/LEBA_20110918.csv',
 '../data/picks_2011/J26A_20111227.csv',
 '../data/picks_2011/BTB_20110813.csv',
 '../data/picks_2011/WISH_20110607.csv',
 '../data/picks_2011/FORK_20110123.csv',
 '../data/picks_2011/YOUB_20110927.csv',
 '../data/picks_2011/KSXB_20111208.csv',
 '../data/picks_2011/J41A_20110903.csv',
 '../data/picks_2011/I02D_20111008.csv',
 '../data/picks_2011/BABR_20110705.csv',
 '../data/picks_2011/MGB_20111103.csv',
 '../data/picks_2011/WISH_20111120.csv',
 '../data/picks_2011/BABR_20111125.csv',
 '../data/picks_2011/KMR_20111126.csv',
 '../data/picks_2011/W09_20110323.csv',
 '../data/picks_2011/M07A_20111209.csv',
 '../data/picks_2011/D03D_20110720.csv',
 '../data/picks_2011/OZB_20110318.csv',
 '../data/picks_2011/WISH_20110308.csv',
 '../data/picks_2011/TAKO_20111212.csv',
 '../data/picks_2011/SNB_20110309.csv',
 '../data/picks_2011/D03D_20111009.csv',
 '../data/picks_2011/I02D_20110905.csv',
 '../data/picks_2011/JCC_20110305.csv',
 '../data/picks_2011/MEGW_20110629.csv',
 '../data/picks_2011/NLLB_20110701.csv',
 '../data/picks_2011/PFB_20110829.csv',
 '../data/picks_2011/FN12A_20110921.csv',
 '../data/picks_2011/DBO_20110626.csv',
 '../data/picks_2011/LEBA_20110714.csv',
 '../data/picks_2011/FN01A_20110812.csv',
 '../data/picks_2011/G03D_20110512.csv',
 '../data/picks_2011/VGZ_20111101.csv',
 '../data/picks_2011/SHB_20110311.csv',
 '../data/picks_2011/M07A_20111126.csv',
 '../data/picks_2011/PGC_20110703.csv',
 '../data/picks_2011/J51A_20111128.csv',
 '../data/picks_2011/LEBA_20110901.csv',
 '../data/picks_2011/SHB_20110702.csv',
 '../data/picks_2011/M03A_20111202.csv',
 '../data/picks_2011/L02D_20110218.csv',
 '../data/picks_2011/KHMB_20110731.csv',
 '../data/picks_2011/W03_20110213.csv',
 '../data/picks_2011/LRIV_20110402.csv',
 '../data/picks_2011/SHB_20110203.csv',
 '../data/picks_2011/KHMB_20110314.csv',
 '../data/picks_2011/LRIV_20110915.csv',
 '../data/picks_2011/TAKO_20110326.csv',
 '../data/picks_2011/M08A_20111102.csv',
 '../data/picks_2011/MEGW_20110703.csv',
 '../data/picks_2011/FISH_20110516.csv',
 '../data/picks_2011/KSXB_20110419.csv',
 '../data/picks_2011/BABR_20110829.csv',
 '../data/picks_2011/K02D_20110125.csv',
 '../data/picks_2011/LEBA_20110622.csv',
 '../data/picks_2011/BABR_20110801.csv',
 '../data/picks_2011/KMR_20110817.csv',
 '../data/picks_2011/M07A_20111119.csv',
 '../data/picks_2011/DBO_20111128.csv',
 '../data/picks_2011/J65A_20111212.csv',
 '../data/picks_2011/L02D_20111203.csv',
 '../data/picks_2011/KHMB_20110428.csv',
 '../data/picks_2011/G03D_20110609.csv',
 '../data/picks_2011/BABR_20110506.csv',
 '../data/picks_2011/FISH_20110727.csv',
 '../data/picks_2011/JCC_20111105.csv',
 '../data/picks_2011/HEBO_20110227.csv',
 '../data/picks_2011/OFR_20111220.csv',
 '../data/picks_2011/J01D_20110917.csv',
 '../data/picks_2011/KSXB_20110804.csv',
 '../data/picks_2011/DBO_20110109.csv',
 '../data/picks_2011/J59A_20111119.csv',
 '../data/picks_2011/FN16A_20111229.csv',
 '../data/picks_2011/MEGW_20110827.csv',
 '../data/picks_2011/J51A_20111129.csv',
 '../data/picks_2011/KMR_20110811.csv',
 '../data/picks_2011/L02D_20110302.csv',
 '../data/picks_2011/MGB_20110912.csv',
 '../data/picks_2011/SHB_20110110.csv',
 '../data/picks_2011/LRIV_20111120.csv',
 '../data/picks_2011/LRIV_20110223.csv',
 '../data/picks_2011/J59A_20111202.csv',
 '../data/picks_2011/KMPB_20111215.csv',
 '../data/picks_2011/VGZ_20111130.csv',
 '../data/picks_2011/PFB_20110420.csv',
 '../data/picks_2011/KRP_20110428.csv',
 '../data/picks_2011/J01D_20111119.csv',
 '../data/picks_2011/K02D_20111218.csv',
 '../data/picks_2011/J01D_20110221.csv',
 '../data/picks_2011/J50A_20111110.csv',
 '../data/picks_2011/DBO_20110410.csv',
 '../data/picks_2011/M02A_20111018.csv',
 '../data/picks_2011/FISH_20110429.csv',
 '../data/picks_2011/JEDS_20110824.csv',
 '../data/picks_2011/JEDS_20110819.csv',
 '../data/picks_2011/WISH_20110906.csv',
 '../data/picks_2011/KSXB_20111006.csv',
 '../data/picks_2011/NLLB_20110816.csv',
 '../data/picks_2011/J01D_20110503.csv',
 '../data/picks_2011/YOUB_20111120.csv',
 '../data/picks_2011/W03_20110226.csv',
 '../data/picks_2011/W03_20110307.csv',
 '../data/picks_2011/J73A_20111117.csv',
 '../data/picks_2011/J42A_20111117.csv',
 '../data/picks_2011/KRP_20110611.csv',
 '../data/picks_2011/J35A_20111215.csv',
 '../data/picks_2011/KMR_20110214.csv',
 '../data/picks_2011/YOUB_20110220.csv',
 '../data/picks_2011/BTB_20110404.csv',
 '../data/picks_2011/J49A_20111125.csv',
 '../data/picks_2011/KMR_20110926.csv',
 '../data/picks_2011/J41A_20111014.csv',
 '../data/picks_2011/KCT_20110717.csv',
 '../data/picks_2011/TAKO_20111011.csv',
 '../data/picks_2011/KSXB_20110607.csv',
 '../data/picks_2011/KHBB_20110422.csv',
 '../data/picks_2011/KMR_20110719.csv',
 '../data/picks_2011/KCT_20111227.csv',
 '../data/picks_2011/W03_20110303.csv',
 '../data/picks_2011/FN08A_20111025.csv',
 '../data/picks_2011/M08A_20111024.csv',
 '../data/picks_2011/J41A_20111220.csv',
 '../data/picks_2011/M06A_20111210.csv',
 '../data/picks_2011/I02D_20110813.csv',
 '../data/picks_2011/NLLB_20110618.csv',
 '../data/picks_2011/HEBO_20110621.csv',
 '../data/picks_2011/J59A_20111029.csv',
 '../data/picks_2011/L02D_20110901.csv',
 '../data/picks_2011/FISH_20110417.csv',
 '../data/picks_2011/OZB_20110910.csv',
 '../data/picks_2011/NLLB_20110729.csv',
 '../data/picks_2011/D03D_20110613.csv',
 '../data/picks_2011/KCT_20111013.csv',
 '../data/picks_2011/KHBB_20110717.csv',
 '../data/picks_2011/OFR_20111209.csv',
 '../data/picks_2011/I03D_20111115.csv',
 '../data/picks_2011/W07_20110129.csv',
 '../data/picks_2011/KRP_20111205.csv',
 '../data/picks_2011/SQM_20110125.csv',
 '../data/picks_2011/VGZ_20111016.csv',
 '../data/picks_2011/KCT_20110926.csv',
 '../data/picks_2011/KHBB_20110930.csv',
 '../data/picks_2011/KHMB_20110702.csv',
 '../data/picks_2011/LRIV_20110904.csv',
 '../data/picks_2011/BTB_20110201.csv',
 '../data/picks_2011/I03D_20111231.csv',
 '../data/picks_2011/D03D_20110409.csv',
 '../data/picks_2011/HEBO_20110126.csv',
 '../data/picks_2011/FN12A_20111222.csv',
 '../data/picks_2011/KRP_20111218.csv',
 '../data/picks_2011/HEBO_20110314.csv',
 '../data/picks_2011/OZB_20110717.csv',
 '../data/picks_2011/KRP_20110530.csv',
 '../data/picks_2011/SNB_20110123.csv',
 '../data/picks_2011/I02D_20110413.csv',
 '../data/picks_2011/SNB_20111004.csv',
 '../data/picks_2011/OFR_20110218.csv',
 '../data/picks_2011/J42A_20111215.csv',
 '../data/picks_2011/BMSB_20110720.csv',
 '../data/picks_2011/SNB_20110804.csv',
 '../data/picks_2011/LRIV_20110714.csv',
 '../data/picks_2011/KSXB_20111205.csv',
 '../data/picks_2011/KBO_20110108.csv',
 '../data/picks_2011/FN14A_20111121.csv',
 '../data/picks_2011/KMR_20110505.csv',
 '../data/picks_2011/I03D_20110114.csv',
 '../data/picks_2011/JCC_20110529.csv',
 '../data/picks_2011/TAKO_20110929.csv',
 '../data/picks_2011/YOUB_20110209.csv',
 '../data/picks_2011/D03D_20110921.csv',
 '../data/picks_2011/J58A_20111020.csv',
 '../data/picks_2011/FN08A_20110804.csv',
 '../data/picks_2011/M07A_20111114.csv',
 '../data/picks_2011/KRMB_20111114.csv',
 '../data/picks_2011/WISH_20110420.csv',
 '../data/picks_2011/FORK_20110718.csv',
 '../data/picks_2011/KMPB_20111121.csv',
 '../data/picks_2011/OZB_20110423.csv',
 '../data/picks_2011/J35A_20111226.csv',
 '../data/picks_2011/TAKO_20111108.csv',
 '../data/picks_2011/MEGW_20110623.csv',
 '../data/picks_2011/KCT_20110807.csv',
 '../data/picks_2011/KRMB_20110929.csv',
 '../data/picks_2011/BTB_20110225.csv',
 '../data/picks_2011/J41A_20110830.csv',
 '../data/picks_2011/FORK_20110606.csv',
 '../data/picks_2011/FN05A_20111126.csv',
 '../data/picks_2011/F04D_20110411.csv',
 '../data/picks_2011/JCC_20110611.csv',
 '../data/picks_2011/FORK_20110318.csv',
 '../data/picks_2011/VGZ_20110228.csv',

In [6]:
len(csv_list)

9759

In [7]:
#  Concatenate all the picks in all the files produced in 1_parallel_detect_picks_elep_all_sta
all_csv =[]


for i in csv_list:
    temp = pd.read_csv(i,index_col=0)
    all_csv.append(temp)
    
df = pd.concat(all_csv, axis=0)

/tmp/ipykernel_135448/3549658960.py:9: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat(all_csv, axis=0)
/tmp/ipykernel_135448/3549658960.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(all_csv, axis=0)

In [8]:
# Print df
df[0:10]

,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival
0,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,NaN,2011-06-07T03:05:53.490000Z
1,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,NaN,2011-06-07T05:12:21.290000Z
2,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,NaN,2011-06-07T05:43:38.615000Z
3,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,NaN,2011-06-07T10:40:58.615000Z
4,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,NaN,2011-06-07T13:20:32.615000Z
5,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,NaN,2011-06-07T17:21:19.640000Z
6,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,2011-06-07T01:25:24.415000Z,NaN
7,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,2011-06-07T04:46:50.365000Z,NaN
8,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,2011-06-07T05:43:45.715000Z,NaN
9,,,UW,,FORK,NaN,47.9475,-124.5662,44.9,,40.0,2011-06-07T00:00:00.015000Z,,,,,,2011-06-07T08:30:19.290000Z,NaN

In [9]:
len(df)

1080113

In [10]:
df.to_csv('../data/datasets_2011/all_picks_2011.csv')

### 1.3 Create a CSV file for picks for the association

In [11]:
# Assign P to P phases in the df
p_phase = df.loc[df['trace_p_arrival'].notna(), 'phase'] = "P"

In [12]:
# Filter the df 
p_stas_picks_phase = df.loc[df['trace_p_arrival'].notna(), ['station_code','trace_p_arrival','phase']]
p_stas_picks_phase

    station_code              trace_p_arrival phase
0           FORK  2011-06-07T03:05:53.490000Z     P
1           FORK  2011-06-07T05:12:21.290000Z     P
2           FORK  2011-06-07T05:43:38.615000Z     P
3           FORK  2011-06-07T10:40:58.615000Z     P
4           FORK  2011-06-07T13:20:32.615000Z     P
..           ...                          ...   ...
866        FN18A  2011-11-12T23:52:07.204000Z     P
867        FN18A  2011-11-12T23:52:10.764000Z     P
868        FN18A  2011-11-12T23:53:21.428000Z     P
869        FN18A  2011-11-12T23:55:47.012000Z     P
870        FN18A  2011-11-12T23:59:42.572000Z     P

[579656 rows x 3 columns]

In [13]:
# Rename the df
_p_stas_picks_phase = p_stas_picks_phase.rename(columns={"station_code": "station", "trace_p_arrival": "time"})
_p_stas_picks_phase

    station                         time phase
0      FORK  2011-06-07T03:05:53.490000Z     P
1      FORK  2011-06-07T05:12:21.290000Z     P
2      FORK  2011-06-07T05:43:38.615000Z     P
3      FORK  2011-06-07T10:40:58.615000Z     P
4      FORK  2011-06-07T13:20:32.615000Z     P
..      ...                          ...   ...
866   FN18A  2011-11-12T23:52:07.204000Z     P
867   FN18A  2011-11-12T23:52:10.764000Z     P
868   FN18A  2011-11-12T23:53:21.428000Z     P
869   FN18A  2011-11-12T23:55:47.012000Z     P
870   FN18A  2011-11-12T23:59:42.572000Z     P

[579656 rows x 3 columns]

In [14]:
# Assign S to S phases in the df
s_phase = df.loc[df['trace_s_arrival'].notna(), 'phase'] = "S"# Filter the df

In [15]:
# Filter the df 
s_stas_picks_phase = df.loc[df['trace_s_arrival'].notna(), ['station_code','trace_s_arrival','phase']]
s_stas_picks_phase

     station_code              trace_s_arrival phase
6            FORK  2011-06-07T01:25:24.415000Z     S
7            FORK  2011-06-07T04:46:50.365000Z     S
8            FORK  2011-06-07T05:43:45.715000Z     S
9            FORK  2011-06-07T08:30:19.290000Z     S
10           FORK  2011-06-07T09:01:18.140000Z     S
...           ...                          ...   ...
1566        FN18A  2011-11-12T23:49:51.956000Z     S
1567        FN18A  2011-11-12T23:51:11.236000Z     S
1568        FN18A  2011-11-12T23:52:11.388000Z     S
1569        FN18A  2011-11-12T23:53:21.436000Z     S
1570        FN18A  2011-11-12T23:59:43.636000Z     S

[500457 rows x 3 columns]

In [16]:
# Rename the df
_s_stas_picks_phase = s_stas_picks_phase.rename(columns={"station_code": "station", "trace_s_arrival": "time"})
_s_stas_picks_phase

     station                         time phase
6       FORK  2011-06-07T01:25:24.415000Z     S
7       FORK  2011-06-07T04:46:50.365000Z     S
8       FORK  2011-06-07T05:43:45.715000Z     S
9       FORK  2011-06-07T08:30:19.290000Z     S
10      FORK  2011-06-07T09:01:18.140000Z     S
...      ...                          ...   ...
1566   FN18A  2011-11-12T23:49:51.956000Z     S
1567   FN18A  2011-11-12T23:51:11.236000Z     S
1568   FN18A  2011-11-12T23:52:11.388000Z     S
1569   FN18A  2011-11-12T23:53:21.436000Z     S
1570   FN18A  2011-11-12T23:59:43.636000Z     S

[500457 rows x 3 columns]

In [17]:
# Concatenate the P and S picks
picks = pd.concat(objs = [_p_stas_picks_phase,_s_stas_picks_phase] , axis=0)
picks

     station                         time phase
0       FORK  2011-06-07T03:05:53.490000Z     P
1       FORK  2011-06-07T05:12:21.290000Z     P
2       FORK  2011-06-07T05:43:38.615000Z     P
3       FORK  2011-06-07T10:40:58.615000Z     P
4       FORK  2011-06-07T13:20:32.615000Z     P
...      ...                          ...   ...
1566   FN18A  2011-11-12T23:49:51.956000Z     S
1567   FN18A  2011-11-12T23:51:11.236000Z     S
1568   FN18A  2011-11-12T23:52:11.388000Z     S
1569   FN18A  2011-11-12T23:53:21.436000Z     S
1570   FN18A  2011-11-12T23:59:43.636000Z     S

[1080113 rows x 3 columns]

In [18]:
# Swap the time and phase columns
picks = picks.iloc[:,[0,2,1]]
picks = picks.reset_index(drop=True)
picks

        station phase                         time
0          FORK     P  2011-06-07T03:05:53.490000Z
1          FORK     P  2011-06-07T05:12:21.290000Z
2          FORK     P  2011-06-07T05:43:38.615000Z
3          FORK     P  2011-06-07T10:40:58.615000Z
4          FORK     P  2011-06-07T13:20:32.615000Z
...         ...   ...                          ...
1080108   FN18A     S  2011-11-12T23:49:51.956000Z
1080109   FN18A     S  2011-11-12T23:51:11.236000Z
1080110   FN18A     S  2011-11-12T23:52:11.388000Z
1080111   FN18A     S  2011-11-12T23:53:21.436000Z
1080112   FN18A     S  2011-11-12T23:59:43.636000Z

[1080113 rows x 3 columns]

In [25]:
# Save the these picks to the data folder
picks.to_csv("../data/datasets_2011/picks_2011.csv")

## Create the stations data frame

In [20]:
# Print the stations for which the picks were detected in 1_parallel_detect_picks_elep_all_sta 
stations = df.drop_duplicates(subset='station_code')
stations

,event_id,source_type,station_network_code,station_channel_code,station_code,station_location_code,station_latitude_deg,station_longitude_deg,station_elevation_m,trace_name,trace_sampling_rate_hz,trace_start_time,trace_S_arrival_sample,trace_P_arrival_sample,trace_S_onset,trace_P_onset,trace_snr_db,trace_s_arrival,trace_p_arrival,phase
0,,,UW,,FORK,NaN,47.947500,-124.566200,44.9,,40.000000,2011-06-07T00:00:00.015000Z,,,,,,NaN,2011-06-07T03:05:53.490000Z,P
0,,,CN,,LZB,NaN,48.612200,-123.824000,794.0,,40.000000,2011-06-04T00:00:00.000000Z,,,,,,NaN,2011-06-04T07:33:23.975000Z,P
0,,,TA,,G03D,NaN,45.211498,-123.264099,222.0,,40.000000,2011-06-27T00:00:00.000000Z,,,,,,NaN,2011-06-27T03:04:10.875000Z,P
0,,,7D,,J33A,NaN,45.106602,-124.570801,-348.7,,50.000000,2011-11-21T00:00:00.010400Z,,,,,,NaN,2011-11-21T02:04:33.750400Z,P
0,,,7A,,W04,NaN,48.531700,-126.890800,-2319.0,,50.000000,2011-02-17T00:00:00.004800Z,,,,,,NaN,2011-02-17T00:03:17.944800Z,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,,,7D,,J25A,NaN,44.472900,-124.621597,-142.8,,50.000000,2011-11-05T00:00:00.006400Z,,,,,,NaN,2011-11-05T00:21:00.806400Z,P
0,,,7D,,J57A,NaN,47.080101,-124.450500,-55.8,,50.000000,2011-10-19T00:00:00.014100Z,,,,,,NaN,2011-10-19T00:24:10.294100Z,P
0,,,7A,,W02,NaN,48.259300,-126.496803,-2133.0,,50.000000,2011-01-01T00:00:00.009800Z,,,,,,NaN,2011-01-01T00:04:10.249800Z,P
0,,,7D,,J43A,NaN,46.137798,-126.172096,-2654.4,,50.000008,2011-10-22T00:00:00.014100Z,,,,,,NaN,2011-10-22T01:05:28.773501Z,P
0,,,7D,,M01A,NaN,49.150398,-126.722099,-132.9,,50.000008,2011-12-30T00:00:00.004600Z,,,,,,NaN,2011-12-30T00:12:54.964482Z,P

In [21]:
# Obtain only the columns you need for assoication
_stations = stations.iloc[:,[4,7,6,8]]
_stations

,station_code,station_longitude_deg,station_latitude_deg,station_elevation_m
0,FORK,-124.566200,47.947500,44.9
0,LZB,-123.824000,48.612200,794.0
0,G03D,-123.264099,45.211498,222.0
0,J33A,-124.570801,45.106602,-348.7
0,W04,-126.890800,48.531700,-2319.0
...,...,...,...,...
0,J25A,-124.621597,44.472900,-142.8
0,J57A,-124.450500,47.080101,-55.8
0,W02,-126.496803,48.259300,-2133.0
0,J43A,-126.172096,46.137798,-2654.4
0,M01A,-126.722099,49.150398,-132.9

In [22]:
# Rename the columns
_stations = _stations.rename(columns={'station_code': 'id', 'station_longitude_deg': 'longitude', 'station_latitude_deg': 'latitude', 'station_elevation_m': 'elevation'})
_stations = _stations.reset_index(drop=True)
_stations

      id   longitude   latitude  elevation
0   FORK -124.566200  47.947500       44.9
1    LZB -123.824000  48.612200      794.0
2   G03D -123.264099  45.211498      222.0
3   J33A -124.570801  45.106602     -348.7
4    W04 -126.890800  48.531700    -2319.0
..   ...         ...        ...        ...
76  J25A -124.621597  44.472900     -142.8
77  J57A -124.450500  47.080101      -55.8
78   W02 -126.496803  48.259300    -2133.0
79  J43A -126.172096  46.137798    -2654.4
80  M01A -126.722099  49.150398     -132.9

[81 rows x 4 columns]

In [24]:
# Create  a csv file
_stations.to_csv('../data/datasets_2011/all_stations_2011.csv')